(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module VALUE.
  Record signature {t : Set} : Type := {
    t := t;
    value : t;
  }.
End VALUE.
Definition VALUE := @VALUE.signature.
Arguments VALUE {_}.

Module Outer.
  Class FArgs {Left_t : Set} := {
    Left : VALUE (t := Left_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition t `{_fargs : FArgs} : Set := Left.(VALUE.t).
  
  Definition get `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Left.(VALUE.t)}
    (flag : bool) : Left.(VALUE.t) :=
    if flag then
      Left.(VALUE.value)
    else
      let '_ := false in
      (@RocqOfOCaml.Basics.unreachable Left.(VALUE.t) _).
  
  Module Child.
    Class FArgs `{_fargs : FArgs} {Right_t : Set} := {
      Right : VALUE (t := Right_t);
    }.
    Arguments Build_FArgs {_ _ _}.
    
    Definition pair_value `{_fargs : FArgs}
      : Left.(VALUE.t) * (Right (FArgs := _fargs)).(VALUE.t) :=
      (Left.(VALUE.value), (Right (FArgs := _fargs)).(VALUE.value)).
    
    Module Child_result.
      Record signature `{_fargs : FArgs} : Type := {
        pair_value : Left.(VALUE.t) * Right.(VALUE.t);
      }.
    End Child_result.
    Definition Child_result `{_fargs : FArgs} := @Child_result.signature _ _ _
      _.
    Arguments Child_result {_ _ _ _}.
    
    (* Child *)
    Definition functor `{_fargs : FArgs} :@Child_result _ _ Right_t _fargs :=
      ((@Child_result.Build_signature _ _ Right_t _fargs pair_value) :
        @Child_result _ _ Right_t _fargs).
  End Child.
  Definition Child `{_fargs : FArgs} {Right_t : Set}
    (Right : VALUE (t := Right_t)) :=
    @Child.functor _ _ Right_t (Child.Build_FArgs Right).
  
  Module Outer_result.
    Record signature `{_fargs : FArgs} : Type := {
      t := Left.(VALUE.t);
      get :
        forall
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Left.(VALUE.t)},
          bool -> Left.(VALUE.t);
    
    }.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _ _.
  Arguments Outer_result {_ _}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :@Outer_result Left_t _fargs :=
    ((@Outer_result.Build_signature Left_t _fargs (fun _ => get)) :
      @Outer_result Left_t _fargs).
End Outer.
Definition Outer {Left_t : Set} (Left : VALUE (t := Left_t)) :=
  @Outer.functor Left_t (Outer.Build_FArgs Left).

Module Int_value.
  Definition t : Set := int.
  
  Definition value : int := 42.
  
  (* Int_value *)
  Definition module :VALUE (t := int) :=
    {|
      VALUE.value := value
    |}.
End Int_value.
Definition Int_value := Int_value.module.

Definition Applied_fargs := Outer.Build_FArgs Int_value.

Definition Applied : Outer.Outer_result (_fargs := Applied_fargs) :=
  (Outer.functor (_fargs := (Applied_fargs ))).
