(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Require TestProject.Provider.

Definition decremented
  `{_rocq_assumption_0 :
    RocqOfOCaml.Basics.Unreachable TestProject.Provider.Counter.t} : TestProject.Provider.Counter.t :=
  TestProject.Provider.decrement TestProject.Provider.one.

Definition directly_decremented
  `{_rocq_assumption_0 :
    RocqOfOCaml.Basics.Unreachable TestProject.Provider.Counter.t} : TestProject.Provider.Counter.t :=
  TestProject.Provider.Counter.pred TestProject.Provider.Counter.zero.
