(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Require Import RocqOfOCaml.ModuleOverrideModel.

Module Counter := RocqOfOCaml.ModuleOverrideModel.

Definition one : RocqOfOCaml.ModuleOverrideModel.t :=
  RocqOfOCaml.ModuleOverrideModel.succ RocqOfOCaml.ModuleOverrideModel.zero.

Definition decrement
  `{_rocq_assumption_0 :
    RocqOfOCaml.Basics.Unreachable RocqOfOCaml.ModuleOverrideModel.t}
  (value : RocqOfOCaml.ModuleOverrideModel.t)
  : RocqOfOCaml.ModuleOverrideModel.t :=
  RocqOfOCaml.ModuleOverrideModel.pred value.
