(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Require TestProject.Provider.

Definition reexport
  `{_rocq_assumption_0 :
    RocqOfOCaml.Basics.Unreachable (RocqOfOCaml.OCamlIarray.t int)}
  `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int} (flag : bool)
  (values : RocqOfOCaml.OCamlIarray.t int)
  : RocqOfOCaml.OCamlIarray.t int * int :=
  (TestProject.Provider.pair_value (_rocq_assumption_0 := _rocq_assumption_0) (_rocq_assumption_1 := _rocq_assumption_1))
    flag values.
