(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition pair_value
  `{_rocq_assumption_0 :
    RocqOfOCaml.Basics.Unreachable (RocqOfOCaml.OCamlIarray.t int)}
  `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int} (flag : bool)
  (values : RocqOfOCaml.OCamlIarray.t int)
  : RocqOfOCaml.OCamlIarray.t int * int :=
  let values :=
    if flag then
      values
    else
      let '_ := false in
      (@RocqOfOCaml.Basics.unreachable (RocqOfOCaml.OCamlIarray.t int) _) in
  let number :=
    if flag then
      0
    else
      let '_ := false in
      (@RocqOfOCaml.Basics.unreachable int _) in
  (values, number).
