(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Base.
  Definition x_value : int := 1.
End Base.

Module Wrapped.
  Definition x_value : int := Base.x_value.
  
  Definition y_value : int := 2.
  
  Module Wrapped_signature.
    Record signature : Set := {
      x_value : int;
      y_value : int;
    }.
  End Wrapped_signature.
  Definition Wrapped_signature := Wrapped_signature.signature.
  
  (* Wrapped *)
  Definition module :Wrapped_signature :=
    {|
      Wrapped_signature.x_value := x_value;
      Wrapped_signature.y_value := y_value
    |}.
End Wrapped.
Definition Wrapped := Wrapped.module.

(** Inclusion of the module [Wrapped] *)
Definition x_value : int := Wrapped.(Wrapped.Wrapped_signature.x_value).

Definition y_value : int := Wrapped.(Wrapped.Wrapped_signature.y_value).

Module Hidden.
  Definition t : Set := string.
  
  Definition make {A : Set} (value : A) : A := value.
  
  Module Hidden_signature.
    Record signature : Set := {
      t := string;
      make : string -> t;
    }.
  End Hidden_signature.
  Definition Hidden_signature := Hidden_signature.signature.
  
  (* Hidden *)
  Definition module :Hidden_signature :=
    {|
      Hidden_signature.make := make
    |}.
End Hidden.
Definition Hidden := Hidden.module.
