(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module First_T_signature.
  Record signature {t : Set} : Set := {
    t := t;
  }.
End First_T_signature.
Definition First_T_signature := @First_T_signature.signature.
Arguments First_T_signature {_}.

Module First.
  Class FArgs {T_t : Set} := {
    T : First_T_signature (t := T_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition id `{_fargs : FArgs} (x_value : T.(First_T_signature.t))
    : T.(First_T_signature.t) := x_value.
  
  Module First_result.
    Record signature `{_fargs : FArgs} : Set := {
      id : T.(First_T_signature.t) -> T.(First_T_signature.t);
    }.
  End First_result.
  Definition First_result `{_fargs : FArgs} := @First_result.signature _ _.
  Arguments First_result {_ _}.
  
  (* First *)
  Definition functor `{_fargs : FArgs} :@First_result T_t _fargs :=
    ({|
      First_result.id (T_t := T_t) (_fargs := _fargs) := (id (_fargs := _fargs))
    |} : @First_result T_t _fargs).
End First.
Definition First {T_t : Set} (T : First_T_signature (t := T_t)) :=
  @First.functor T_t (First.Build_FArgs T).

Module Second_T_signature.
  Record signature {t : Set} : Set := {
    t := t;
  }.
End Second_T_signature.
Definition Second_T_signature := @Second_T_signature.signature.
Arguments Second_T_signature {_}.

Module Second.
  Class FArgs {T_t : Set} := {
    T : Second_T_signature (t := T_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition id `{_fargs : FArgs} (x_value : T.(Second_T_signature.t))
    : T.(Second_T_signature.t) := x_value.
  
  Module Second_result.
    Record signature `{_fargs : FArgs} : Set := {
      id : T.(Second_T_signature.t) -> T.(Second_T_signature.t);
    }.
  End Second_result.
  Definition Second_result `{_fargs : FArgs} := @Second_result.signature _ _.
  Arguments Second_result {_ _}.
  
  (* Second *)
  Definition functor `{_fargs : FArgs} :@Second_result T_t _fargs :=
    ({|
      Second_result.id (T_t := T_t) (_fargs := _fargs) :=
        (id (_fargs := _fargs))
    |} : @Second_result T_t _fargs).
End Second.
Definition Second {T_t : Set} (T : Second_T_signature (t := T_t)) :=
  @Second.functor T_t (Second.Build_FArgs T).

Definition First_int_fargs :=
  First.Build_FArgs
    (let t : Set := int in
    ((ltac:(constructor) : First_T_signature (t := t)) :
      First_T_signature (t := t))).

Definition First_int : First.First_result (_fargs := First_int_fargs) :=
  First
    (let t : Set := int in
    ((ltac:(constructor) : First_T_signature (t := t)) :
      First_T_signature (t := t))).

Definition Second_bool_fargs :=
  Second.Build_FArgs
    (let t : Set := bool in
    ((ltac:(constructor) : Second_T_signature (t := t)) :
      Second_T_signature (t := t))).

Definition Second_bool : Second.Second_result (_fargs := Second_bool_fargs) :=
  Second
    (let t : Set := bool in
    ((ltac:(constructor) : Second_T_signature (t := t)) :
      Second_T_signature (t := t))).
