(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module VALUE.
  Record signature {t : Set} : Set := {
    t := t;
    value : t;
  }.
End VALUE.
Definition VALUE := @VALUE.signature.
Arguments VALUE {_}.

Module Outer.
  Class FArgs {Left_t : Set} := {
    Left : VALUE (t := Left_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition _left `{_fargs : FArgs} : Left.(VALUE.t) := Left.(VALUE.value).
  
  Module Child.
    Class FArgs `{_fargs : FArgs} {Right_t : Set} := {
      Right : VALUE (t := Right_t);
    }.
    Arguments Build_FArgs {_ _ _}.
    
    Definition pair_value `{_fargs : FArgs}
      : Left.(VALUE.t) * Right.(VALUE.t) :=
      (Left.(VALUE.value), Right.(VALUE.value)).
    
    Module Child_result.
      Record signature `{_fargs : FArgs} : Set := {
        pair_value : Left.(VALUE.t) * Right.(VALUE.t);
      }.
    End Child_result.
    Definition Child_result `{_fargs : FArgs} := @Child_result.signature _ _ _
      _.
    Arguments Child_result {_ _ _ _}.
    
    (* Child *)
    Definition functor `{_fargs : FArgs} :@Child_result _ _ Right_t _fargs :=
      ({|
        Child_result.pair_value (Right_t := Right_t) (_fargs := _fargs) :=
          (pair_value (_fargs := _fargs))
      |} : @Child_result _ _ Right_t _fargs).
  End Child.
  Definition Child `{_fargs : FArgs} {Right_t : Set}
    (Right : VALUE (t := Right_t)) :=
    @Child.functor _ _ Right_t (Child.Build_FArgs Right).
  
  Module Outer_result.
    Record signature `{_fargs : FArgs} : Set := {
      _left : Left.(VALUE.t);
    
    }.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _ _.
  Arguments Outer_result {_ _}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :@Outer_result Left_t _fargs :=
    ({|
      Outer_result._left (Left_t := Left_t) (_fargs := _fargs) :=
        (_left (_fargs := _fargs))
    |} : @Outer_result Left_t _fargs).
End Outer.
Definition Outer {Left_t : Set} (Left : VALUE (t := Left_t)) :=
  @Outer.functor Left_t (Outer.Build_FArgs Left).

Module Use.
  Class FArgs {Value_t : Set} := {
    Value : VALUE (t := Value_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition Applied_fargs `{_fargs : FArgs} := Outer.Build_FArgs Value.
  
  Definition Applied `{_fargs : FArgs} :
    Outer.Outer_result (_fargs := Applied_fargs) := Outer Value.
  
  Definition Result_fargs `{_fargs : FArgs} :=
    (Outer.Child.Build_FArgs (_fargs := Applied_fargs)) Value.
  
  Definition Result `{_fargs : FArgs} :
    Outer.Child.Child_result (_fargs := Result_fargs) :=
    (Outer.Child (_fargs := Applied_fargs)) Value.
  
  Module Use_result.
    Record signature `{_fargs : FArgs} : Set := {
      Applied : Outer.Outer_result (_fargs := Applied_fargs);
      Result : Outer.Child.Child_result (_fargs := Result_fargs);
    }.
  End Use_result.
  Definition Use_result `{_fargs : FArgs} := @Use_result.signature _ _.
  Arguments Use_result {_ _}.
  
  (* Use *)
  Definition functor `{_fargs : FArgs} :@Use_result Value_t _fargs :=
    ({|
      Use_result.Applied (Value_t := Value_t) (_fargs := _fargs) :=
        (Applied (_fargs := _fargs));
      Use_result.Result (Value_t := Value_t) (_fargs := _fargs) :=
        (Result (_fargs := _fargs))
    |} : @Use_result Value_t _fargs).
End Use.
Definition Use {Value_t : Set} (Value : VALUE (t := Value_t)) :=
  @Use.functor Value_t (Use.Build_FArgs Value).
