(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Complex_Field_signature.
  Record signature {t : Set} : Type := {
    t := t;
    zero : t;
  }.
End Complex_Field_signature.
Definition Complex_Field_signature := @Complex_Field_signature.signature.
Arguments Complex_Field_signature {_}.

Module Complex.
  Class FArgs {Field_t : Set} := {
    Field : Complex_Field_signature (t := Field_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module t.
    Record record `{_fargs : FArgs} : Set := Build {
      re : Field.(Complex_Field_signature.t);
      im : Field.(Complex_Field_signature.t);
    }.
    Definition with_re `{_fargs : FArgs} re (r : record) :=
      Build _ _ re r.(im).
    Definition with_im `{_fargs : FArgs} im (r : record) :=
      Build _ _ r.(re) im.
  End t.
  Definition t `{_fargs : FArgs} := t.record.
  
  Definition zero `{_fargs : FArgs} : t :=
    {| t.re := Field.(Complex_Field_signature.zero);
      t.im := Field.(Complex_Field_signature.zero); |}.
  
  Definition swap `{_fargs : FArgs} (value : t) : t :=
    {| t.re := value.(t.im); t.im := value.(t.re); |}.
  
  Module Complex_result.
    Record signature `{_fargs : FArgs} {t : Set} : Type := {
      t := t;
      t__rocq_record_make :
        Field.(Complex_Field_signature.t) ->
        Field.(Complex_Field_signature.t) -> t;
      t__rocq_record_get_re : t -> Field.(Complex_Field_signature.t);
      t__rocq_record_get_im : t -> Field.(Complex_Field_signature.t);
      zero : t;
      swap : t -> t;
    }.
  End Complex_result.
  Definition Complex_result `{_fargs : FArgs} := @Complex_result.signature _ _.
  Arguments Complex_result {_ _ _}.
  
  (* Complex *)
  Definition functor `{_fargs : FArgs} :Complex_result (t := _) :=
    {|
      Complex_result.t__rocq_record_make :=
        fun _rocq_record_field_re _rocq_record_field_im =>
          {| t.re := _rocq_record_field_re; t.im := _rocq_record_field_im; |};
      Complex_result.t__rocq_record_get_re :=
        fun _rocq_record_value => _rocq_record_value.(t.re);
      Complex_result.t__rocq_record_get_im :=
        fun _rocq_record_value => _rocq_record_value.(t.im);
      Complex_result.zero := zero;
      Complex_result.swap := swap
    |}.
End Complex.
Definition Complex {Field_t : Set}
  (Field : Complex_Field_signature (t := Field_t)) :=
  @Complex.functor Field_t (Complex.Build_FArgs Field).

Module Int_field.
  Definition t : Set := int.
  
  Definition zero : int := 0.
End Int_field.

Definition Applied_fargs :=
  Complex.Build_FArgs
    ({|
      Complex_Field_signature.zero := Int_field.zero
    |} : Complex_Field_signature (t := Int_field.t)).

Definition Applied : Complex.Complex_result (_fargs := Applied_fargs) :=
  (Complex.functor (_fargs := (Applied_fargs ))).

Definition components (value : Applied.(Complex.Complex_result.t))
  : Int_field.t * Int_field.t := (value.(Complex.t.re), value.(Complex.t.im)).

Definition result_value : Applied.(Complex.Complex_result.t) :=
  Applied.(Complex.Complex_result.swap) Applied.(Complex.Complex_result.zero).
