(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition values : array int := [ 1; 2; 3 ].

Definition empty : array int := [ ].
