(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition checked_identity {A : Set} (x_value : A) : A :=
  let '_ :=
    assert unit (RocqOfOCaml.Basics.Stdlib.polymorphic_equal x_value x_value) in
  x_value.

Definition unreachable (function_parameter : unit) : int :=
  let '_ := function_parameter in
  assert int false.
