(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition map {A : Set}
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A}
  (function_parameter : option A) : A :=
  match function_parameter with
  | Some value => value
  | None =>
    let '_ := false in
    (@RocqOfOCaml.Basics.unreachable A _)
  end.

Module Base.
  Definition map {A : Set} (value : A) : A := value.
End Base.

Module Nested.
  Include Base.
  
  Module Nested_signature.
    Record signature : Type := {
      map : int -> int;
    }.
  End Nested_signature.
  Definition Nested_signature := Nested_signature.signature.
  
  (* Nested *)
  Definition module :Nested_signature :=
    {|
      Nested_signature.map := map
    |}.
End Nested.
Definition Nested := Nested.module.

Module Partial_base.
  Definition find {A : Set}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A}
    (function_parameter : option A) : A :=
    match function_parameter with
    | Some value => value
    | None =>
      let '_ := false in
      (@RocqOfOCaml.Basics.unreachable A _)
    end.
End Partial_base.

Module Partial_nested.
  Include Partial_base.
  
  Module Partial_nested_signature.
    Record signature : Type := {
      find :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int},
          option int -> int;
    }.
  End Partial_nested_signature.
  Definition Partial_nested_signature := Partial_nested_signature.signature.
  
  (* Partial_nested *)
  Definition module :Partial_nested_signature :=
    {|
      Partial_nested_signature.find _ := find
    |}.
End Partial_nested.
Definition Partial_nested := Partial_nested.module.

Module ARGUMENT.
  Record signature : Type := {
    token : unit;
  }.
End ARGUMENT.
Definition ARGUMENT := ARGUMENT.signature.

Module Make.
  Class FArgs := {
    Argument : ARGUMENT;
  }.
  
  Module Map.
    Definition find `{_fargs : FArgs} {A : Set}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A}
      (function_parameter : option A) : A :=
      match function_parameter with
      | Some value => value
      | None =>
        let '_ := false in
        (@RocqOfOCaml.Basics.unreachable A _)
      end.
  End Map.
  
  Module Make_result.
    Record signature `{_fargs : FArgs} : Type := {
      Map_find :
        forall {A : Set}
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A},
          option A -> A;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result _fargs :=
    ((@Make_result.Build_signature _fargs (fun _ _ => Map.find)) :
      @Make_result _fargs).
End Make.
Definition Make (Argument : ARGUMENT) :=
  @Make.functor (Make.Build_FArgs Argument).

Module KEY.
  Record signature {t : Set} : Type := {
    t := t;
  }.
End KEY.
Definition KEY := @KEY.signature.
Arguments KEY {_}.

Module Keyed.
  Class FArgs {Key_t : Set} := {
    Key : KEY (t := Key_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module Map.
    Definition key `{_fargs : FArgs} : Set := Key.(KEY.t).
    
    Definition min_binding `{_fargs : FArgs} {a : Set}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable (key * a)}
      (entries : list (key * a)) : key * a :=
      match entries with
      | Datatypes.cons entry _ => entry
      | [] =>
        let '_ := false in
        (@RocqOfOCaml.Basics.unreachable (key * a) _)
      end.
  End Map.
  
  Module Keyed_result.
    Record signature `{_fargs : FArgs} : Type := {
      Map_key := Key.(KEY.t);
      Map_min_binding :
        forall {a : Set}
          `{_rocq_assumption_0 :
            RocqOfOCaml.Basics.Unreachable (Key.(KEY.t) * a)},
          list (Map_key * a) -> Map_key * a;
    }.
  End Keyed_result.
  Definition Keyed_result `{_fargs : FArgs} := @Keyed_result.signature _ _.
  Arguments Keyed_result {_ _}.
  
  (* Keyed *)
  Definition functor `{_fargs : FArgs} :@Keyed_result Key_t _fargs :=
    ((@Keyed_result.Build_signature Key_t _fargs (fun _ _ => Map.min_binding)) :
      @Keyed_result Key_t _fargs).
End Keyed.
Definition Keyed {Key_t : Set} (Key : KEY (t := Key_t)) :=
  @Keyed.functor Key_t (Keyed.Build_FArgs Key).

Module Int_key.
  Definition t : Set := int.
End Int_key.

Definition Int_keyed_fargs :=
  Keyed.Build_FArgs
    ((ltac:(constructor) : KEY (t := Int_key.t)) : KEY (t := Int_key.t)).

Definition Int_keyed : Keyed.Keyed_result (_fargs := Int_keyed_fargs) :=
  (Keyed.functor (_fargs := (Int_keyed_fargs ))).

Definition first_string
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable (int * string)}
  (entries : list (int * string)) : int * string :=
  (Int_keyed.(Keyed.Keyed_result.Map_min_binding)
    (_rocq_assumption_0 := _rocq_assumption_0)) entries.
