(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module ARG.
  Record signature : Type := {
    token : unit;
  }.
End ARG.
Definition ARG := ARG.signature.

Module Make.
  Class FArgs := {
    Argument : ARG;
  }.

  Definition trigger `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit} : unit :=
    if false then tt else (@RocqOfOCaml.Basics.unreachable unit _).

  Module Nested.
    Definition use `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
      (function_parameter : unit) : unit :=
      let '_ := function_parameter in
      let '_ := Argument.(ARG.token) in
      trigger.
  End Nested.

  Module Make_result.
    Record signature `{_fargs : FArgs} : Type := {
      trigger :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}, unit;
      Nested_use :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit},
          unit -> unit;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_}.

  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result _fargs :=
    ((@Make_result.Build_signature _fargs (fun _ => trigger)
      (fun _ => Nested.use)) : @Make_result _fargs).
End Make.
Definition Make (Argument : ARG) := @Make.functor (Make.Build_FArgs Argument).

Module Instantiate.
  Class FArgs := {
    Argument : ARG;
  }.

  Definition Make_include_fargs `{_fargs : FArgs} := Make.Build_FArgs Argument.

  Definition Make_include `{_fargs : FArgs} :
    Make.Make_result (_fargs := Make_include_fargs) := Make Argument.

  (** Inclusion of the module [Make_include] *)
  Definition trigger `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit} : unit :=
    Make_include.(Make.Make_result.trigger).

  Module Nested.
    Definition use `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit} : unit -> unit
      := Make_include.(Make.Make_result.Nested_use).
  End Nested.

  Module Instantiate_result.
    Record signature `{_fargs : FArgs} : Type := {
      trigger :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}, unit;
      Nested_use :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit},
          unit -> unit;
    }.
  End Instantiate_result.
  Definition Instantiate_result `{_fargs : FArgs} :=
    @Instantiate_result.signature _.
  Arguments Instantiate_result {_}.

  (* Instantiate *)
  Definition functor `{_fargs : FArgs} :@Instantiate_result _fargs :=
    ((@Instantiate_result.Build_signature _fargs (fun _ => trigger)
      (fun _ => Nested.use)) : @Instantiate_result _fargs).
End Instantiate.
Definition Instantiate (Argument : ARG) :=
  @Instantiate.functor (Instantiate.Build_FArgs Argument).
