(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition leaf
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int} : int :=
  let '_ := false in
  (@RocqOfOCaml.Basics.unreachable int _).

Definition middle
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int}
  (function_parameter : unit) : int :=
  let '_ := function_parameter in
  leaf.

Definition root
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int}
  `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable unit}
  (function_parameter : unit) : int :=
  let '_ := function_parameter in
  let '_ := if true then tt else (@RocqOfOCaml.Basics.unreachable unit _) in
  middle tt.
