(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition unit_value : unit := tt.

Definition empty_list {A : Set} : list A := nil.

Definition singleton {A : Set} (value : A) : list A := Datatypes.cons value nil.
