(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Status.
  Inductive t : Set :=
  | Success : t
  | Failure : t
  | Stack_overflow : t
  | Ok : t
  | Error : t.
  
  Definition to_string (function_parameter : t) : string :=
    match function_parameter with
    | Success => "success"
    | Failure => "failure"
    | Stack_overflow => "stack overflow"
    | Ok => "ok"
    | Error => "error"
    end.
End Status.
