(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module PARAM.
  Record signature {t : Set} : Type := {
    t := t;
    fallback : t;
  }.
End PARAM.
Definition PARAM := @PARAM.signature.
Arguments PARAM {_}.

Module Generated.
  Class FArgs {Param_t : Set} := {
    Param : PARAM (t := Param_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition t `{_fargs : FArgs} : Set := Param.(PARAM.t).
  
  Definition make `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable t} (value : t) : t :=
    if true then
      value
    else
      let '_ := false in
      (@RocqOfOCaml.Basics.unreachable t _).
  
  Module Generated_result.
    Record signature `{_fargs : FArgs} : Type := {
      t := Param.(PARAM.t);
      make :
        forall
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Param.(PARAM.t)},
          t -> t;
    }.
  End Generated_result.
  Definition Generated_result `{_fargs : FArgs} := @Generated_result.signature _
    _.
  Arguments Generated_result {_ _}.
  
  (* Generated *)
  Definition functor `{_fargs : FArgs} :@Generated_result Param_t _fargs :=
    ((@Generated_result.Build_signature Param_t _fargs (fun _ => make)) :
      @Generated_result Param_t _fargs).
End Generated.
Definition Generated {Param_t : Set} (Param : PARAM (t := Param_t)) :=
  @Generated.functor Param_t (Generated.Build_FArgs Param).

Module Outer.
  Class FArgs {Param_t : Set} := {
    Param : PARAM (t := Param_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition Applied_fargs `{_fargs : FArgs} := Generated.Build_FArgs Param.
  
  Definition Applied `{_fargs : FArgs} :
    Generated.Generated_result (_fargs := Applied_fargs) := (Generated.functor
    (_fargs := (Applied_fargs ))).
  
  Module state.
    Record record `{_fargs : FArgs} : Set := Build {
      value : Param.(PARAM.t);
    }.
    Definition with_value `{_fargs : FArgs} value (r : record) :=
      Build _ _ value.
  End state.
  Definition state `{_fargs : FArgs} := state.record.
  
  Definition initial `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Param.(PARAM.t)} : state :=
    {|
      state.value :=
        ((Applied (_fargs := _fargs)).(Generated.Generated_result.make)
          (_rocq_assumption_0 := _rocq_assumption_0)) Param.(PARAM.fallback); |}.
  
  Module Outer_result.
    Record signature `{_fargs : FArgs} {state : Set} : Type := {
      Applied : Generated.Generated_result (_fargs := Applied_fargs);
      state := state;
      state__rocq_record_make : Param.(PARAM.t) -> state;
      state__rocq_record_get_value : state -> Param.(PARAM.t);
      initial :
        forall
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Param.(PARAM.t)},
          state;
    }.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _ _.
  Arguments Outer_result {_ _ _}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :Outer_result (state := _) :=
    {|
      Outer_result.Applied := Applied;
      Outer_result.state__rocq_record_make :=
        fun _rocq_record_field_value =>
          {| state.value := _rocq_record_field_value; |};
      Outer_result.state__rocq_record_get_value :=
        fun _rocq_record_value => _rocq_record_value.(state.value);
      Outer_result.initial _ := initial
    |}.
End Outer.
Definition Outer {Param_t : Set} (Param : PARAM (t := Param_t)) :=
  @Outer.functor Param_t (Outer.Build_FArgs Param).
