(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition op_pointdollarlparenrparen {A : Set} (values : list A) (index : int)
  : A := RocqOfOCaml.OCamlList.nth values index.

Definition get {A : Set} (values : list A) (index : int) : A :=
  op_pointdollarlparenrparen values index.
