(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module TYPE.
  Record signature {t : Set} : Type := {
    t := t;
  }.
End TYPE.
Definition TYPE := @TYPE.signature.
Arguments TYPE {_}.

Module Box.
  Class FArgs {Value_t : Set} := {
    Value : TYPE (t := Value_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition t `{_fargs : FArgs} : Set := Value.(TYPE.t).
  
  Definition id `{_fargs : FArgs} (value : t) : t := value.
  
  Module Box_result.
    Record signature `{_fargs : FArgs} : Type := {
      t := Value.(TYPE.t);
      id : t -> t;
    }.
  End Box_result.
  Definition Box_result `{_fargs : FArgs} := @Box_result.signature _ _.
  Arguments Box_result {_ _}.
  
  (* Box *)
  Definition functor `{_fargs : FArgs} :@Box_result Value_t _fargs :=
    ((@Box_result.Build_signature Value_t _fargs id) :
      @Box_result Value_t _fargs).
End Box.
Definition Box {Value_t : Set} (Value : TYPE (t := Value_t)) :=
  @Box.functor Value_t (Box.Build_FArgs Value).

Module Consume_Input_signature.
  Record signature {Value_t : Set} {Value : TYPE (t := Value_t)} : Type := {
    value : Value.(TYPE.t);
  }.
End Consume_Input_signature.
Definition Consume_Input_signature {Value_t : Set} {Value : TYPE (t := Value_t)}
  := @Consume_Input_signature.signature Value_t Value.

Module Consume.
  Class FArgs {Value_t : Set} := {
    Value : TYPE (t := Value_t);
    Input : (Consume_Input_signature (Value := Value));
  }.
  Arguments Build_FArgs {_}.
  
  Definition Value_box_fargs `{_fargs : FArgs} := Box.Build_FArgs Value.
  
  Definition Value_box `{_fargs : FArgs} :
    Box.Box_result (_fargs := Value_box_fargs) := (Box.functor
    (_fargs := (Value_box_fargs ))).
  
  Definition result_value `{_fargs : FArgs} : Value.(TYPE.t) :=
    (Value_box (_fargs := _fargs)).(Box.Box_result.id)
      Input.(Consume_Input_signature.value).
  
  Module Consume_result.
    Record signature `{_fargs : FArgs} : Type := {
      Value_box : Box.Box_result (_fargs := Value_box_fargs);
      result_value : Value.(TYPE.t);
    }.
  End Consume_result.
  Definition Consume_result `{_fargs : FArgs} := @Consume_result.signature _ _.
  Arguments Consume_result {_ _}.
  
  (* Consume *)
  Definition functor `{_fargs : FArgs} :@Consume_result Value_t _fargs :=
    ((@Consume_result.Build_signature Value_t _fargs Value_box result_value) :
      @Consume_result Value_t _fargs).
End Consume.
Definition Consume {Value_t : Set}
  (Value : TYPE (t := Value_t))
  (Input : (Consume_Input_signature (Value := Value))) :=
  @Consume.functor Value_t (Consume.Build_FArgs Value Input).

Module Int_value.
  Definition t : Set := int.
End Int_value.

Module Input.
  Definition value : int := 42.
End Input.

Definition Result_fargs :=
  Consume.Build_FArgs
    ((ltac:(constructor) : TYPE (t := Int_value.t)) : TYPE (t := Int_value.t))
    ({|
      Consume_Input_signature.value := Input.value
    |} : Consume_Input_signature).

Definition Result : Consume.Consume_result (_fargs := Result_fargs) :=
  (Consume.functor (_fargs := (Result_fargs ))).

Definition result_value : int := Result.(Consume.Consume_result.result_value).

Module Variant.
  Class FArgs {Value_t : Set} := {
    Value : TYPE (t := Value_t);
  }.
  Arguments Build_FArgs {_}.
  
  Inductive t `{_fargs : FArgs} : Set :=
  | Point : Value.(TYPE.t) -> t
  | Infinity : t.
  
  Definition infinity `{_fargs : FArgs} : t := Infinity.
  
  Module Variant_result.
    Record signature `{_fargs : FArgs} {t : Set} : Type := {
      t := t;
      infinity : t;
    }.
  End Variant_result.
  Definition Variant_result `{_fargs : FArgs} := @Variant_result.signature _ _.
  Arguments Variant_result {_ _ _}.
  
  (* Variant *)
  Definition functor `{_fargs : FArgs} :Variant_result (t := _) :=
    {|
      Variant_result.infinity := infinity
    |}.
End Variant.
Definition Variant {Value_t : Set} (Value : TYPE (t := Value_t)) :=
  @Variant.functor Value_t (Variant.Build_FArgs Value).

Definition Int_variant_fargs :=
  Variant.Build_FArgs
    ((ltac:(constructor) : TYPE (t := Int_value.t)) : TYPE (t := Int_value.t)).

Definition Int_variant : Variant.Variant_result (_fargs := Int_variant_fargs) :=
  (Variant.functor (_fargs := (Int_variant_fargs ))).

Definition point : Int_variant.(Variant.Variant_result.t) := Variant.Point 42.

Definition point_value
  (function_parameter : Int_variant.(Variant.Variant_result.t)) : Int_value.t :=
  match function_parameter with
  | Variant.Point value => value
  | Variant.Infinity => 0
  end.
