(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Error.
  Inductive invalid_block : Set :=
  | Gas_above_limit : invalid_block
  | Invalid_number : invalid_block.
  
  Inductive invalid_transaction : Set :=
  | Gas_above_limit_invalid_transaction : invalid_transaction
  | Invalid_nonce : invalid_transaction.
  
  Definition block_error : invalid_block := Gas_above_limit.
  
  Definition transaction_error : invalid_transaction :=
    Gas_above_limit_invalid_transaction.
  
  Definition is_block_gas_error (_error : invalid_block) : bool :=
    match _error with
    | Gas_above_limit => true
    | Invalid_number => false
    end.
  
  Definition is_transaction_gas_error (_error : invalid_transaction) : bool :=
    match _error with
    | Gas_above_limit_invalid_transaction => true
    | Invalid_nonce => false
    end.
End Error.
