(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Parameter configured_equal : forall {A : Set}, A -> A -> bool.
Definition file_marker := true.
Definition opaque : Set := int -> int.

Definition equal_opaque (x_value : opaque) (y_value : opaque) : bool :=
  configured_equal x_value y_value.
