(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition keep : int := 1.

Module Nested.
  Definition keep_nested : int := 3.
End Nested.
