(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Local := RocqOfOCaml.OCamlSeq.

Module ARG.
  Record signature : Type := {
    marker : int;
  }.
End ARG.
Definition ARG := ARG.signature.

Module Make.
  Class FArgs := {
    Argument : ARG;
  }.

  Definition marker `{_fargs : FArgs} : int := Argument.(ARG.marker).

  Module Seq.
    Definition t `{_fargs : FArgs} (a : Set) : Set := RocqOfOCaml.OCamlSeq.t a.

    Definition synthetic_signature_identity `{_fargs : FArgs} {a : Set}
      (values : RocqOfOCaml.OCamlSeq.t a) : RocqOfOCaml.OCamlSeq.t a := values.
  End Seq.

  Module Make_result.
    Record signature `{_fargs : FArgs} : Type := {
      marker : int;
      Seq_t := fun (a : Set) => RocqOfOCaml.OCamlSeq.t a;
      Seq_synthetic_signature_identity : forall {a : Set} , Seq_t a -> Seq_t a;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_}.

  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result _fargs :=
    ((@Make_result.Build_signature _fargs marker
      (fun _ => Seq.synthetic_signature_identity)) : @Make_result _fargs).
End Make.
Definition Make (Argument : ARG) := @Make.functor (Make.Build_FArgs Argument).

Definition identity {a : Set} (values : Local.t a) : Local.t a := values.

Definition bounded
  `{_rocq_assumption_0 :
    RocqOfOCaml.Basics.Unreachable (RocqOfOCaml.OCamlSeq.t int)} (count : int)
  (start : int) : RocqOfOCaml.OCamlSeq.t int :=
  RocqOfOCaml.OCamlSeq.range count start.
