(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Input.
  Record signature {t : Set} : Set := {
    t := t;
    default : t;
  }.
End Input.
Definition Input := @Input.signature.
Arguments Input {_}.

Module Make.
  Class FArgs {Value_t : Set} := {
    Value : Input (t := Value_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition t `{_fargs : FArgs} : Set := option Value.(Input.t).
  
  Definition default `{_fargs : FArgs} : option Value.(Input.t) :=
    Some Value.(Input.default).
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :Input (t := option Value.(Input.t)) :=
    {|
      Input.default := (default (_fargs := _fargs))
    |}.
End Make.
Definition Make {Value_t : Set} (Value : Input (t := Value_t)) :=
  @Make.functor Value_t (Make.Build_FArgs Value).

Module Make_alias := Make.
Definition Make_alias := @Make.
Arguments Make_alias : default implicits.

Module Value.
  Definition t : Set := int.
  
  Definition default : int := 3.
  
  (* Value *)
  Definition module :Input (t := int) :=
    {|
      Input.default := default
    |}.
End Value.
Definition Value := Value.module.

Definition Result := Make_alias Value.

Definition result_value : Result.(Input.t) := Result.(Input.default).
