(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Consumer_M_signature.
  Record signature {Pair_t : Set} : Type := {
    Pair_t := Pair_t;
    Pair_t__rocq_record_make : int -> int -> Pair_t;
    Pair_t__rocq_record_get_left : Pair_t -> int;
    Pair_t__rocq_record_get_right : Pair_t -> int;
  }.
End Consumer_M_signature.
Definition Consumer_M_signature := @Consumer_M_signature.signature.
Arguments Consumer_M_signature {_}.

Module Consumer.
  Class FArgs {M_Pair_t : Set} := {
    M : Consumer_M_signature (Pair_t := M_Pair_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition make `{_fargs : FArgs} (_left : int) (_right : int)
    : M.(Consumer_M_signature.Pair_t) :=
    M.(Consumer_M_signature.Pair_t__rocq_record_make) _left _right.
  
  Definition swap `{_fargs : FArgs} (value : M.(Consumer_M_signature.Pair_t))
    : M.(Consumer_M_signature.Pair_t) :=
    M.(Consumer_M_signature.Pair_t__rocq_record_make)
      (M.(Consumer_M_signature.Pair_t__rocq_record_get_right) value)
      (M.(Consumer_M_signature.Pair_t__rocq_record_get_left) value).
  
  Module Consumer_result.
    Record signature `{_fargs : FArgs} : Type := {
      make : int -> int -> M.(Consumer_M_signature.Pair_t);
      swap : M.(Consumer_M_signature.Pair_t) -> M.(Consumer_M_signature.Pair_t);
    }.
  End Consumer_result.
  Definition Consumer_result `{_fargs : FArgs} := @Consumer_result.signature _
    _.
  Arguments Consumer_result {_ _}.
  
  (* Consumer *)
  Definition functor `{_fargs : FArgs} :@Consumer_result M_Pair_t _fargs :=
    ((@Consumer_result.Build_signature M_Pair_t _fargs make swap) :
      @Consumer_result M_Pair_t _fargs).
End Consumer.
Definition Consumer {M_Pair_t : Set}
  (M : Consumer_M_signature (Pair_t := M_Pair_t)) :=
  @Consumer.functor M_Pair_t (Consumer.Build_FArgs M).

Module Actual.
  Module Pair.
    Module t.
      Record record : Set := Build {
        _left : int;
        _right : int;
      }.
      Definition with__left _left (r : record) :=
        Build _left r.(_right).
      Definition with__right _right (r : record) :=
        Build r.(_left) _right.
    End t.
    Definition t := t.record.
  End Pair.
End Actual.

Definition Applied_fargs :=
  Consumer.Build_FArgs
    ({|
      Consumer_M_signature.Pair_t__rocq_record_make :=
        fun _rocq_record_field_left _rocq_record_field_right =>
          {| Actual.Pair.t._left := _rocq_record_field_left;
            Actual.Pair.t._right := _rocq_record_field_right; |};
      Consumer_M_signature.Pair_t__rocq_record_get_left :=
        fun _rocq_record_value => _rocq_record_value.(Actual.Pair.t._left);
      Consumer_M_signature.Pair_t__rocq_record_get_right :=
        fun _rocq_record_value => _rocq_record_value.(Actual.Pair.t._right)
    |} : Consumer_M_signature (Pair_t := Actual.Pair.t)).

Definition Applied : Consumer.Consumer_result (_fargs := Applied_fargs) :=
  (Consumer.functor (_fargs := (Applied_fargs ))).

Definition result_value : Actual.Pair.t :=
  Applied.(Consumer.Consumer_result.swap)
    (Applied.(Consumer.Consumer_result.make) 1 2).
