(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module t.
  Record record : Set := Build {
    value : int;
  }.
  Definition with_value value (r : record) :=
    Build value.
End t.
Definition t := t.record.

Definition get (x_value : t) : int := x_value.(t.value).
