(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module INPUT.
  Record signature : Set := {
    value : int;
  }.
End INPUT.
Definition INPUT := INPUT.signature.

Module OUTPUT.
  Record signature : Set := {
    result_value : int;
  }.
End OUTPUT.
Definition OUTPUT := OUTPUT.signature.

Module Produce.
  Class FArgs := {
    Input : INPUT;
  }.
  
  Definition result_value `{_fargs : FArgs} : int := Input.(INPUT.value).
  
  Definition extra `{_fargs : FArgs} : int := Z.add Input.(INPUT.value) 1.
  
  Module Produce_result.
    Record signature `{_fargs : FArgs} : Set := {
      result_value : int;
      extra : int;
    }.
  End Produce_result.
  Definition Produce_result `{_fargs : FArgs} := @Produce_result.signature _.
  Arguments Produce_result {_}.
  
  (* Produce *)
  Definition functor `{_fargs : FArgs} :@Produce_result _fargs :=
    ({|
      Produce_result.result_value (_fargs := _fargs) :=
        (result_value (_fargs := _fargs));
      Produce_result.extra (_fargs := _fargs) := (extra (_fargs := _fargs))
    |} : @Produce_result _fargs).
End Produce.
Definition Produce (Input : INPUT) :=
  @Produce.functor (Produce.Build_FArgs Input).

Module Consume.
  Class FArgs := {
    Producer : forall (Input : INPUT), OUTPUT;
    Input : INPUT;
  }.
  
  Definition Result `{_fargs : FArgs} := Producer Input.
  
  Module Consume_result.
    Record signature `{_fargs : FArgs} : Set := {
      Result : OUTPUT;
    }.
  End Consume_result.
  Definition Consume_result `{_fargs : FArgs} := @Consume_result.signature _.
  Arguments Consume_result {_}.
  
  (* Consume *)
  Definition functor `{_fargs : FArgs} :@Consume_result _fargs :=
    ({|
      Consume_result.Result (_fargs := _fargs) := (Result (_fargs := _fargs))
    |} : @Consume_result _fargs).
End Consume.
Definition Consume (Producer : forall (Input : INPUT), OUTPUT) (Input : INPUT)
  := @Consume.functor (Consume.Build_FArgs Producer Input).

Module Concrete.
  Definition value : int := 41.
  
  (* Concrete *)
  Definition module :INPUT :=
    {|
      INPUT.value := value
    |}.
End Concrete.
Definition Concrete := Concrete.module.

Definition Applied_fargs :=
  Consume.Build_FArgs
    (fun (Input : INPUT) =>
      let module_coercion := Produce Input in
      {|
        OUTPUT.result_value :=
          module_coercion.(Produce.Produce_result.result_value)
      |}) Concrete.

Definition Applied : Consume.Consume_result (_fargs := Applied_fargs) :=
  Consume
    (fun (Input : INPUT) =>
      let module_coercion := Produce Input in
      {|
        OUTPUT.result_value :=
          module_coercion.(Produce.Produce_result.result_value)
      |}) Concrete.
