(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module BOX.
  Record signature {t : Set} : Type := {
    t := t;
    empty : t;
  }.
End BOX.
Definition BOX := @BOX.signature.
Arguments BOX {_}.

Module ARGUMENT.
  Record signature : Type := {
    token : unit;
  }.
End ARGUMENT.
Definition ARGUMENT := ARGUMENT.signature.

Module DefaultArgument.
  Definition token : unit := tt.

  (* DefaultArgument *)
  Definition module :ARGUMENT :=
    {|
      ARGUMENT.token := token
    |}.
End DefaultArgument.
Definition DefaultArgument := DefaultArgument.module.

Module Box.
  Class FArgs := {
    Argument : ARGUMENT;
  }.

  Definition t `{_fargs : FArgs} : Set := list int.

  Definition empty `{_fargs : FArgs} {A : Set} : list A := nil.

  (* Box *)
  Definition functor `{_fargs : FArgs} :BOX (t := t) :=
    {|
      BOX.empty := empty
    |}.
End Box.
Definition Box (Argument : ARGUMENT) := @Box.functor (Box.Build_FArgs Argument).

Module State.
  Definition Applied := Box DefaultArgument.
End State.

Module Reexport.
  Definition Applied := State.Applied.

  Definition contents : Set := Applied.(BOX.t).

  Definition empty : Applied.(BOX.t) := Applied.(BOX.empty).
End Reexport.
