(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Make_Token_signature.
  Record signature : Type := {
    token : unit;
  }.
End Make_Token_signature.
Definition Make_Token_signature := Make_Token_signature.signature.

Module Make.
  Class FArgs := {
    Token : Make_Token_signature;
  }.
  
  Definition t `{_fargs : FArgs} : Set := int.
  
  Definition Collection `{_fargs : FArgs} :=
    RocqOfOCaml.OCamlSet.Make
      (let t : Set := t in
      let compare := RocqOfOCaml.OCamlInt.compare in
      ({|
        RocqOfOCaml.OCamlMap.OrderedType.compare := compare
      |} : RocqOfOCaml.OCamlMap.OrderedType (t := t))).
  
  Module Make_result.
    Record signature `{_fargs : FArgs} {Collection_t : Set} : Type := {
      t := int;
      Collection : RocqOfOCaml.OCamlSet.S (elt := int) (t := Collection_t);
      Collection_t := Collection_t;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_ _}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :Make_result (Collection_t := _) :=
    {|
      Make_result.Collection := Collection
    |}.
End Make.
Definition Make (Token : Make_Token_signature) :=
  @Make.functor (Make.Build_FArgs Token).

Module Token.
  Definition token : unit := tt.
End Token.

Module Int_collection.
  Definition Make_include_fargs :=
    Make.Build_FArgs
      ({|
        Make_Token_signature.token := Token.token
      |} : Make_Token_signature).
  
  Definition Make_include : Make.Make_result (_fargs := Make_include_fargs) :=
    (Make.functor (_fargs := (Make_include_fargs ))).
  
  (** Inclusion of the module [Make_include] *)
  Section _rocq_include_assumptions_t.
  #[local] Existing Instance Make_include_fargs.
  
  Definition t := Make_include.(Make.Make_result.t).
  End _rocq_include_assumptions_t.
  
  Module Collection.
    Definition elt :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.elt).
    
    Definition t :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.t).
    
    Definition empty :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.empty).
    
    Definition add :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.add).
    
    Definition singleton :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.singleton).
    
    Definition remove :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.remove).
    
    Definition union :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.union).
    
    Definition inter :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.inter).
    
    Definition disjoint :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.disjoint).
    
    Definition diff :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.diff).
    
    Definition cardinal :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.cardinal).
    
    Definition elements :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.elements).
    
    Definition min_elt
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.min_elt).
    
    Definition min_elt_opt :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.min_elt_opt).
    
    Definition max_elt
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.max_elt).
    
    Definition max_elt_opt :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.max_elt_opt).
    
    Definition choose `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt}
      :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.choose).
    
    Definition choose_opt :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.choose_opt).
    
    Definition find `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt}
      :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.find).
    
    Definition find_opt :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.find_opt).
    
    Definition find_first
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.find_first).
    
    Definition find_first_opt :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.find_first_opt).
    
    Definition find_last
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.find_last).
    
    Definition find_last_opt :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.find_last_opt).
    
    Definition iter :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.iter).
    
    Definition fold {acc : Set} : (elt -> acc -> acc) -> t -> acc -> acc :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.fold).
    
    Definition map :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.map).
    
    Definition filter :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.filter).
    
    Definition filter_map :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.filter_map).
    
    Definition partition :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.partition).
    
    Definition split :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.split).
    
    Definition is_empty :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.is_empty).
    
    Definition mem :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.mem).
    
    Definition equal :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.equal).
    
    Definition compare :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.compare).
    
    Definition subset :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.subset).
    
    Definition for_all :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.for_all).
    
    Definition _exists :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S._exists).
    
    Definition to_list :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.to_list).
    
    Definition of_list :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.of_list).
    
    Definition to_seq_from :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.to_seq_from).
    
    Definition to_seq :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.to_seq).
    
    Definition to_rev_seq :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.to_rev_seq).
    
    Definition add_seq :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.add_seq).
    
    Definition of_seq :=
      Make_include.(Make.Make_result.Collection).(RocqOfOCaml.OCamlSet.S.of_seq).
  End Collection.
  
  Section _rocq_include_assumptions_Collection.
  #[local] Existing Instance Make_include_fargs.
  
  Definition Collection := Make_include.(Make.Make_result.Collection).
  End _rocq_include_assumptions_Collection.
End Int_collection.
