(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module FIELD.
  Record signature {t : Set} : Type := {
    t := t;
    one : t;
  }.
End FIELD.
Definition FIELD := @FIELD.signature.
Arguments FIELD {_}.

Module Ring.
  Class FArgs {Field_t : Set} := {
    Field : FIELD (t := Field_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition t `{_fargs : FArgs} : Set := list Field.(FIELD.t).
  
  Module Ring_result.
    Record signature `{_fargs : FArgs} : Type := {
      t := list Field.(FIELD.t);
    }.
  End Ring_result.
  Definition Ring_result `{_fargs : FArgs} := @Ring_result.signature _ _.
  Arguments Ring_result {_ _}.
  
  (* Ring *)
  Definition functor `{_fargs : FArgs} :@Ring_result Field_t _fargs :=
    ((@Ring_result.Build_signature Field_t _fargs) : @Ring_result Field_t _fargs).
End Ring.
Definition Ring {Field_t : Set} (Field : FIELD (t := Field_t)) :=
  @Ring.functor Field_t (Ring.Build_FArgs Field).

Module Include_applied_manifest_Modulus_signature.
  Record signature {Field_t : Set} {Field : FIELD (t := Field_t)} : Type := {
    modulus : (Ring Field).(Ring.Ring_result.t);
  }.
End Include_applied_manifest_Modulus_signature.
Definition Include_applied_manifest_Modulus_signature {Field_t : Set}
  {Field : FIELD (t := Field_t)} :=
  @Include_applied_manifest_Modulus_signature.signature Field_t Field.

Module Include_applied_manifest.
  Class FArgs {Field_t : Set} := {
    Field : FIELD (t := Field_t);
    Modulus : (Include_applied_manifest_Modulus_signature (Field := Field));
  }.
  Arguments Build_FArgs {_}.
  
  (** Inclusion of the module [Modulus] *)
  Definition modulus `{_fargs : FArgs} : (Ring Field).(Ring.Ring_result.t) :=
    Modulus.(Include_applied_manifest_Modulus_signature.modulus).
  
  Module Include_applied_manifest_result.
    Record signature `{_fargs : FArgs} : Type := {
      modulus : (Ring Field).(Ring.Ring_result.t);
    }.
  End Include_applied_manifest_result.
  Definition Include_applied_manifest_result `{_fargs : FArgs} :=
    @Include_applied_manifest_result.signature _ _.
  Arguments Include_applied_manifest_result {_ _}.
  
  (* Include_applied_manifest *)
  Definition functor `{_fargs : FArgs}
    :@Include_applied_manifest_result Field_t _fargs :=
    ((@Include_applied_manifest_result.Build_signature Field_t _fargs modulus) :
      @Include_applied_manifest_result Field_t _fargs).
End Include_applied_manifest.
Definition Include_applied_manifest {Field_t : Set}
  (Field : FIELD (t := Field_t))
  (Modulus : (Include_applied_manifest_Modulus_signature (Field := Field))) :=
  @Include_applied_manifest.functor Field_t
    (Include_applied_manifest.Build_FArgs Field Modulus).

Module Base.
  Definition t : Set := int.
  
  Definition one : int := 1.
  
  (* Base *)
  Definition module :FIELD (t := int) :=
    {|
      FIELD.one := one
    |}.
End Base.
Definition Base := Base.module.

Module Result.
  Definition Include_applied_manifest_include_fargs :=
    Include_applied_manifest.Build_FArgs Base
      (let modulus := Datatypes.cons Base.(FIELD.one) nil in
      ({|
        Include_applied_manifest_Modulus_signature.modulus := modulus
      |} : Include_applied_manifest_Modulus_signature)).
  
  Definition Include_applied_manifest_include :
    Include_applied_manifest.Include_applied_manifest_result
      (_fargs := Include_applied_manifest_include_fargs) :=
    (Include_applied_manifest.functor
    (_fargs := (Include_applied_manifest_include_fargs ))).
  
  (** Inclusion of the module [Include_applied_manifest_include] *)
  Section _rocq_include_assumptions_modulus.
  #[local] Existing Instance Include_applied_manifest_include_fargs.
  
  Definition modulus :=
    Include_applied_manifest_include.(Include_applied_manifest.Include_applied_manifest_result.modulus).
  End _rocq_include_assumptions_modulus.
End Result.
