(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Fixed_Width_signature.
  Record signature : Type := {
    value : int;
  }.
End Fixed_Width_signature.
Definition Fixed_Width_signature := Fixed_Width_signature.signature.

Module Fixed.
  Class FArgs := {
    Width : Fixed_Width_signature;
  }.
  
  Definition t `{_fargs : FArgs} : Set := string.
  
  Definition init `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
    (f_value : int -> ascii) : string :=
    RocqOfOCaml.OCamlString.init
      (RocqOfOCaml.OCamlOption.get (Some Width.(Fixed_Width_signature.value)))
      f_value.
  
  Definition get `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable ascii}
    (value : string) (index : int) : ascii :=
    RocqOfOCaml.OCamlString.get value index.
  
  Definition map `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
    `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable ascii}
    (f_value : ascii -> ascii) (value : string) : string :=
    (init (_rocq_assumption_0 := _rocq_assumption_0)
      (_rocq_assumption_1 := _rocq_assumption_1))
      (fun (index : int) =>
        f_value ((get (_rocq_assumption_0 := _rocq_assumption_2)) value index)).
  
  Module Fixed_result.
    Record signature `{_fargs : FArgs} : Type := {
      t := string;
      init :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
          `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int},
          (int -> ascii) -> string;
      get :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable ascii},
          string -> int -> ascii;
      map :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
          `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
          `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable ascii},
          (ascii -> ascii) -> string -> string;
    }.
  End Fixed_result.
  Definition Fixed_result `{_fargs : FArgs} := @Fixed_result.signature _.
  Arguments Fixed_result {_}.
  
  (* Fixed *)
  Definition functor `{_fargs : FArgs} :@Fixed_result _fargs :=
    ((@Fixed_result.Build_signature _fargs (fun _ _ => init) (fun _ => get)
      (fun _ _ _ => map)) : @Fixed_result _fargs).
End Fixed.
Definition Fixed (Width : Fixed_Width_signature) :=
  @Fixed.functor (Fixed.Build_FArgs Width).

Module B20.
  Definition Fixed_include_fargs :=
    Fixed.Build_FArgs
      (let value := 20 in
      ({|
        Fixed_Width_signature.value := value
      |} : Fixed_Width_signature)).
  
  Definition Fixed_include : Fixed.Fixed_result (_fargs := Fixed_include_fargs)
    := (Fixed.functor (_fargs := (Fixed_include_fargs ))).
  
  (** Inclusion of the module [Fixed_include] *)
  Section _rocq_include_assumptions_t.
  #[local] Existing Instance Fixed_include_fargs.
  
  Definition t := Fixed_include.(Fixed.Fixed_result.t).
  
  Definition init `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable t}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int} :=
    Fixed_include.(Fixed.Fixed_result.init) (_rocq_assumption_0 :=
      _rocq_assumption_0) (_rocq_assumption_1 := _rocq_assumption_1).
  
  Definition get `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable ascii} :=
    Fixed_include.(Fixed.Fixed_result.get) (_rocq_assumption_0 :=
      _rocq_assumption_0).
  
  Definition map `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable t}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
    `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable ascii} :=
    Fixed_include.(Fixed.Fixed_result.map) (_rocq_assumption_0 :=
      _rocq_assumption_0) (_rocq_assumption_1 := _rocq_assumption_1)
      (_rocq_assumption_2 := _rocq_assumption_2).
  End _rocq_include_assumptions_t.
End B20.

Definition B32_fargs :=
  Fixed.Build_FArgs
    (let value := 32 in
    ({|
      Fixed_Width_signature.value := value
    |} : Fixed_Width_signature)).

Definition B32 : Fixed.Fixed_result (_fargs := B32_fargs) := (Fixed.functor
  (_fargs := (B32_fargs ))).

Definition map
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable B20.t}
  `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
  `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable ascii} : (ascii -> ascii)
  -> string -> string :=
  (B20.map (_rocq_assumption_0 := _rocq_assumption_0)
    (_rocq_assumption_1 := _rocq_assumption_1)
    (_rocq_assumption_2 := _rocq_assumption_2)).

Definition make
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
  `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int} (char : ascii)
  : string :=
  (B32.(Fixed.Fixed_result.init) (_rocq_assumption_0 := _rocq_assumption_0)
    (_rocq_assumption_1 := _rocq_assumption_1))
    (fun (function_parameter : int) =>
      let '_ := function_parameter in
      char).
