(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module CORE.
  Record signature {t : Set -> Set} : Set := {
    t := t;
    _return : forall {a : Set} , a -> t a;
  }.
End CORE.
Definition CORE := @CORE.signature.
Arguments CORE {_}.

Module Extend.
  Class FArgs {Monad_t : Set -> Set} := {
    Monad : CORE (t := Monad_t);
  }.
  Arguments Build_FArgs {_}.
  
  (** Inclusion of the module [Monad] *)
  Definition t `{_fargs : FArgs} (a : Set) := Monad.(CORE.t) a.
  
  Definition _return `{_fargs : FArgs} {a : Set} : a -> t a :=
    Monad.(CORE._return).
  
  (* Extend *)
  Definition functor `{_fargs : FArgs}
    :CORE (t := fun (a : Set) => Monad.(CORE.t) a) :=
    {|
      CORE._return _ := (_return (_fargs := _fargs))
    |}.
End Extend.
Definition Extend {Monad_t : Set -> Set} (Monad : CORE (t := Monad_t)) :=
  @Extend.functor Monad_t (Extend.Build_FArgs Monad).

Module WITH_GET.
  Record signature {t : Set -> Set} : Set := {
    t := t;
    _return : forall {a : Set} , a -> t a;
    get : t int;
  }.
End WITH_GET.
Definition WITH_GET := @WITH_GET.signature.
Arguments WITH_GET {_}.

Module Base.
  Definition t (a : Set) : Set := option a.
  
  Definition _return {a : Set} (value : a) : t a := Some value.
  
  Definition get : t int := Some 0.
  
  (* Base *)
  Definition module :WITH_GET (t := fun (a : Set) => option a) :=
    {|
      WITH_GET._return _ := _return;
      WITH_GET.get := get
    |}.
End Base.
Definition Base := Base.module.

Module Make.
  Class FArgs {Monad_t : Set -> Set} := {
    Monad : WITH_GET (t := Monad_t);
  }.
  Arguments Build_FArgs {_}.
  
  (** Inclusion of the module [Monad] *)
  Definition get `{_fargs : FArgs} : Monad.(WITH_GET.t) int :=
    Monad.(WITH_GET.get).
  
  Definition Extend_include `{_fargs : FArgs} :=
    Extend
      ({|
        CORE._return _ := Monad.(WITH_GET._return)
      |} : CORE (t := Monad.(WITH_GET.t))).
  
  (** Inclusion of the module [Extend_include] *)
  Definition t `{_fargs : FArgs} (a : Set) := Extend_include.(CORE.t) a.
  
  Definition _return `{_fargs : FArgs} {a : Set} : a -> t a :=
    Extend_include.(CORE._return).
  
  (* Make *)
  Definition functor `{_fargs : FArgs}
    :WITH_GET (t := fun (a : Set) => Monad.(WITH_GET.t) a) :=
    {|
      WITH_GET.get := (get (_fargs := _fargs));
      WITH_GET._return _ := (_return (_fargs := _fargs))
    |}.
End Make.
Definition Make {Monad_t : Set -> Set} (Monad : WITH_GET (t := Monad_t)) :=
  @Make.functor Monad_t (Make.Build_FArgs Monad).

Module Result.
  Definition Make_include := Make Base.
  
  (** Inclusion of the module [Make_include] *)
  Definition get : option int := Make_include.(WITH_GET.get).
  
  Definition t (a : Set) := Make_include.(WITH_GET.t) a.
  
  Definition _return {a : Set} : a -> t a := Make_include.(WITH_GET._return).
  
  (* Result *)
  Definition module :WITH_GET (t := fun (a : Set) => option a) :=
    {|
      WITH_GET.get := get;
      WITH_GET._return _ := _return
    |}.
End Result.
Definition Result := Result.module.
