(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Base_Ignored_signature.
  Inductive signature : Type :=
  | Build_signature : signature.
End Base_Ignored_signature.
Definition Base_Ignored_signature := Base_Ignored_signature.signature.

Module Base.
  Class FArgs := {
    Ignored : Base_Ignored_signature;
  }.
  
  Definition _Set `{_fargs : FArgs} :=
    RocqOfOCaml.OCamlSet.Make
      ({|
        RocqOfOCaml.OCamlMap.OrderedType.compare := RocqOfOCaml.OCamlInt.compare
      |} : RocqOfOCaml.OCamlMap.OrderedType (t := RocqOfOCaml.OCamlInt.t)).
  
  Module Map.
    Definition keys `{_fargs : FArgs} (function_parameter : unit)
      : _Set.(RocqOfOCaml.OCamlSet.S.t) :=
      let '_ := function_parameter in
      _Set.(RocqOfOCaml.OCamlSet.S.empty).
  End Map.
  
  Module Base_result.
    Record signature `{_fargs : FArgs} {Set_t : Set} : Type := {
      _Set : RocqOfOCaml.OCamlSet.S (elt := int) (t := Set_t);
      Map_keys : unit -> Set_t;
      Set_t := Set_t;
    }.
  End Base_result.
  Definition Base_result `{_fargs : FArgs} := @Base_result.signature _.
  Arguments Base_result {_ _}.
  
  (* Base *)
  Definition functor `{_fargs : FArgs} :Base_result (Set_t := _) :=
    {|
      Base_result._Set := _Set;
      Base_result.Map_keys := Map.keys
    |}.
End Base.
Definition Base (Ignored : Base_Ignored_signature) :=
  @Base.functor (Base.Build_FArgs Ignored).

Module Wrapper.
  Class FArgs := {
    Ignored : Base_Ignored_signature;
  }.
  
  Definition Base_include_fargs `{_fargs : FArgs} := Base.Build_FArgs Ignored.
  
  Definition Base_include `{_fargs : FArgs} :
    Base.Base_result (_fargs := Base_include_fargs) := (Base.functor
    (_fargs := (Base_include_fargs ))).
  
  (** Inclusion of the module [Base_include] *)
  Module _Set.
    Definition elt `{_fargs : FArgs} :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.elt).
    
    Definition t `{_fargs : FArgs} :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.t).
    
    Definition empty `{_fargs : FArgs} : t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.empty).
    
    Definition add `{_fargs : FArgs} : elt -> t -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.add).
    
    Definition singleton `{_fargs : FArgs} : elt -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.singleton).
    
    Definition remove `{_fargs : FArgs} : elt -> t -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.remove).
    
    Definition union `{_fargs : FArgs} : t -> t -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.union).
    
    Definition inter `{_fargs : FArgs} : t -> t -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.inter).
    
    Definition disjoint `{_fargs : FArgs} : t -> t -> bool :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.disjoint).
    
    Definition diff `{_fargs : FArgs} : t -> t -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.diff).
    
    Definition cardinal `{_fargs : FArgs} : t -> int :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.cardinal).
    
    Definition elements `{_fargs : FArgs} : t -> list elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.elements).
    
    Definition min_elt `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} : t -> elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.min_elt).
    
    Definition min_elt_opt `{_fargs : FArgs} : t -> option elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.min_elt_opt).
    
    Definition max_elt `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} : t -> elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.max_elt).
    
    Definition max_elt_opt `{_fargs : FArgs} : t -> option elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.max_elt_opt).
    
    Definition choose `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} : t -> elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.choose).
    
    Definition choose_opt `{_fargs : FArgs} : t -> option elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.choose_opt).
    
    Definition find `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :
      elt -> t -> elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.find).
    
    Definition find_opt `{_fargs : FArgs} : elt -> t -> option elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.find_opt).
    
    Definition find_first `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :
      (elt -> bool) -> t -> elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.find_first).
    
    Definition find_first_opt `{_fargs : FArgs} :
      (elt -> bool) -> t -> option elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.find_first_opt).
    
    Definition find_last `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :
      (elt -> bool) -> t -> elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.find_last).
    
    Definition find_last_opt `{_fargs : FArgs} :
      (elt -> bool) -> t -> option elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.find_last_opt).
    
    Definition iter `{_fargs : FArgs} : (elt -> unit) -> t -> unit :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.iter).
    
    Definition fold `{_fargs : FArgs} {acc : Set} :
      (elt -> acc -> acc) -> t -> acc -> acc :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.fold).
    
    Definition map `{_fargs : FArgs} : (elt -> elt) -> t -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.map).
    
    Definition filter `{_fargs : FArgs} : (elt -> bool) -> t -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.filter).
    
    Definition filter_map `{_fargs : FArgs} : (elt -> option elt) -> t -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.filter_map).
    
    Definition partition `{_fargs : FArgs} : (elt -> bool) -> t -> t * t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.partition).
    
    Definition split `{_fargs : FArgs} : elt -> t -> t * bool * t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.split).
    
    Definition is_empty `{_fargs : FArgs} : t -> bool :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.is_empty).
    
    Definition mem `{_fargs : FArgs} : elt -> t -> bool :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.mem).
    
    Definition equal `{_fargs : FArgs} : t -> t -> bool :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.equal).
    
    Definition compare `{_fargs : FArgs} : t -> t -> int :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.compare).
    
    Definition subset `{_fargs : FArgs} : t -> t -> bool :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.subset).
    
    Definition for_all `{_fargs : FArgs} : (elt -> bool) -> t -> bool :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.for_all).
    
    Definition _exists `{_fargs : FArgs} : (elt -> bool) -> t -> bool :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S._exists).
    
    Definition to_list `{_fargs : FArgs} : t -> list elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.to_list).
    
    Definition of_list `{_fargs : FArgs} : list elt -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.of_list).
    
    Definition to_seq_from `{_fargs : FArgs} :
      elt -> t -> RocqOfOCaml.OCamlSeq.t elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.to_seq_from).
    
    Definition to_seq `{_fargs : FArgs} : t -> RocqOfOCaml.OCamlSeq.t elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.to_seq).
    
    Definition to_rev_seq `{_fargs : FArgs} : t -> RocqOfOCaml.OCamlSeq.t elt :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.to_rev_seq).
    
    Definition add_seq `{_fargs : FArgs} : RocqOfOCaml.OCamlSeq.t elt -> t -> t
      := Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.add_seq).
    
    Definition of_seq `{_fargs : FArgs} : RocqOfOCaml.OCamlSeq.t elt -> t :=
      Base_include.(Base.Base_result._Set).(RocqOfOCaml.OCamlSet.S.of_seq).
  End _Set.
  
  Definition _Set `{_fargs : FArgs} :=
    (Base_include (_fargs := _fargs)).(Base.Base_result._Set).
  
  Module Map.
    Definition keys `{_fargs : FArgs} : unit -> _Set.t :=
      Base_include.(Base.Base_result.Map_keys).
  End Map.
  
  Definition marker `{_fargs : FArgs} : unit := tt.
  
  Module Wrapper_result.
    Record signature `{_fargs : FArgs} {Set_t : Set} : Type := {
      _Set : RocqOfOCaml.OCamlSet.S (elt := int) (t := Set_t);
      Map_keys : unit -> Set_t;
      marker : unit;
      Set_t := Set_t;
    }.
  End Wrapper_result.
  Definition Wrapper_result `{_fargs : FArgs} := @Wrapper_result.signature _.
  Arguments Wrapper_result {_ _}.
  
  (* Wrapper *)
  Definition functor `{_fargs : FArgs} :Wrapper_result (Set_t := _) :=
    {|
      Wrapper_result._Set := _Set;
      Wrapper_result.Map_keys := Map.keys;
      Wrapper_result.marker := marker
    |}.
End Wrapper.
Definition Wrapper (Ignored : Base_Ignored_signature) :=
  @Wrapper.functor (Wrapper.Build_FArgs Ignored).

Definition Result_fargs :=
  Wrapper.Build_FArgs
    ((ltac:(constructor) : Base_Ignored_signature) : Base_Ignored_signature).

Definition Result : Wrapper.Wrapper_result (_fargs := Result_fargs) :=
  (Wrapper.functor (_fargs := (Result_fargs ))).

Module Copy.
  (** Inclusion of the module [Result] *)
  Module _Set.
    Definition elt :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.elt).
    
    Definition t :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.t).
    
    Definition empty :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.empty).
    
    Definition add :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.add).
    
    Definition singleton :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.singleton).
    
    Definition remove :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.remove).
    
    Definition union :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.union).
    
    Definition inter :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.inter).
    
    Definition disjoint :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.disjoint).
    
    Definition diff :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.diff).
    
    Definition cardinal :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.cardinal).
    
    Definition elements :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.elements).
    
    Definition min_elt
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.min_elt).
    
    Definition min_elt_opt :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.min_elt_opt).
    
    Definition max_elt
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.max_elt).
    
    Definition max_elt_opt :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.max_elt_opt).
    
    Definition choose `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt}
      := Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.choose).
    
    Definition choose_opt :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.choose_opt).
    
    Definition find `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt}
      := Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.find).
    
    Definition find_opt :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.find_opt).
    
    Definition find_first
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.find_first).
    
    Definition find_first_opt :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.find_first_opt).
    
    Definition find_last
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable elt} :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.find_last).
    
    Definition find_last_opt :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.find_last_opt).
    
    Definition iter :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.iter).
    
    Definition fold {acc : Set} : (elt -> acc -> acc) -> t -> acc -> acc :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.fold).
    
    Definition map :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.map).
    
    Definition filter :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.filter).
    
    Definition filter_map :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.filter_map).
    
    Definition partition :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.partition).
    
    Definition split :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.split).
    
    Definition is_empty :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.is_empty).
    
    Definition mem :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.mem).
    
    Definition equal :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.equal).
    
    Definition compare :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.compare).
    
    Definition subset :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.subset).
    
    Definition for_all :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.for_all).
    
    Definition _exists :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S._exists).
    
    Definition to_list :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.to_list).
    
    Definition of_list :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.of_list).
    
    Definition to_seq_from :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.to_seq_from).
    
    Definition to_seq :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.to_seq).
    
    Definition to_rev_seq :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.to_rev_seq).
    
    Definition add_seq :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.add_seq).
    
    Definition of_seq :=
      Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.of_seq).
  End _Set.
  
  Definition _Set := Result.(Wrapper.Wrapper_result._Set).
  
  Module Map.
    Definition keys := Result.(Wrapper.Wrapper_result.Map_keys).
  End Map.
  
  Definition marker := Result.(Wrapper.Wrapper_result.marker).
End Copy.

Definition keys
  : Result.(Wrapper.Wrapper_result._Set).(RocqOfOCaml.OCamlSet.S.t) :=
  Copy.Map.keys tt.
