(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.
From Stdlib Require Import Program.Wf.

Module VALUE.
  Record signature {t : Set} : Type := {
    t := t;
    zero : t;
    equal : t -> t -> bool;
  }.
End VALUE.
Definition VALUE := @VALUE.signature.
Arguments VALUE {_}.

Module Container.
  Class FArgs {Value_t : Set} := {
    Value : VALUE (t := Value_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module Impl.
    Definition impl `{_fargs : FArgs} : Set :=
      RocqOfOCaml.OCamlIarray.t Value.(VALUE.t).
    
    Definition t `{_fargs : FArgs} : Set := impl.
    
    Program Definition normalize `{_fargs : FArgs}
      `{_rocq_assumption_0 :
        RocqOfOCaml.Basics.Unreachable
          (RocqOfOCaml.OCamlIarray.t Value.(VALUE.t))}
      `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable impl}
      `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable Value.(VALUE.t)}
      (values : impl) : impl :=
      let _rocq_measure (_rocq_state : int) : nat :=
        RocqOfOCaml.Basics.well_founded_measure
        "Container.Impl.normalize.last_nonzero" (_fargs, values, _rocq_state) in
      let _rocq_body :
        (forall _rocq_state : int,
          (forall _rocq_next : int, ltof int _rocq_measure _rocq_next
            _rocq_state -> int) -> int) :=
        (fun _rocq_state _rocq_recurse =>
          let i_value := _rocq_state in
          if
            andb (Z.geb i_value 0)
              (Value.(VALUE.equal)
                (RocqOfOCaml.OCamlIarray.get values i_value)
                Value.(VALUE.zero))
          then
            _rocq_recurse (Z.sub i_value 1) _
          else
            i_value) in
      let _rocq_fix := @Fix int (ltof int _rocq_measure) (well_founded_ltof int
        _rocq_measure) (fun _ => int) _rocq_body in
      let last_nonzero (i_value : int) : int := _rocq_fix i_value in
      let last := last_nonzero (Z.sub (RocqOfOCaml.OCamlIarray.length values) 1)
        in
      if
        equiv_decb last (Z.sub (RocqOfOCaml.OCamlIarray.length values) 1)
      then
        values
      else
        RocqOfOCaml.OCamlIarray.init (Z.add last 1)
          (fun (i_value : int) => RocqOfOCaml.OCamlIarray.get values i_value).
    
    Admit Obligations.
    
    Module Impl_signature.
      Record signature `{_fargs : FArgs} : Type := {
        impl := RocqOfOCaml.OCamlIarray.t Value.(VALUE.t);
        t := impl;
        normalize :
          forall
            `{_rocq_assumption_0 :
              RocqOfOCaml.Basics.Unreachable Value.(VALUE.t)}
            `{_rocq_assumption_1 :
              RocqOfOCaml.Basics.Unreachable
                (RocqOfOCaml.OCamlIarray.t Value.(VALUE.t))}, impl -> t;
      }.
    End Impl_signature.
    Definition Impl_signature `{_fargs : FArgs} := @Impl_signature.signature _
      _.
    Arguments Impl_signature {_ _}.
    
    (* Impl *)
    Definition module `{_fargs : FArgs} :Impl_signature :=
      {|
        Impl_signature.normalize _ _ := normalize
      |}.
  End Impl.
  Definition Impl `{_fargs : FArgs} := Impl.module.
  
  (** Inclusion of the module [Impl] *)
  Definition impl `{_fargs : FArgs} := Impl.(Impl.Impl_signature.impl).
  
  Definition t `{_fargs : FArgs} := Impl.(Impl.Impl_signature.t).
  
  Definition normalize `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Value.(VALUE.t)}
    `{_rocq_assumption_1 :
      RocqOfOCaml.Basics.Unreachable (RocqOfOCaml.OCamlIarray.t Value.(VALUE.t))}
    : impl -> Impl.(Impl.Impl_signature.t) :=
    Impl.(Impl.Impl_signature.normalize) (_rocq_assumption_0 :=
      _rocq_assumption_0) (_rocq_assumption_1 := _rocq_assumption_1).
  
  Definition init `{_fargs : FArgs}
    `{_rocq_assumption_0 :
      RocqOfOCaml.Basics.Unreachable (RocqOfOCaml.OCamlIarray.t Value.(VALUE.t))}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable impl}
    `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable Value.(VALUE.t)}
    (length : int) (make : int -> Value.(VALUE.t))
    : Impl.(Impl.Impl_signature.impl) :=
    (normalize (_rocq_assumption_0 := _rocq_assumption_2)
      (_rocq_assumption_1 := _rocq_assumption_0))
      (RocqOfOCaml.OCamlIarray.init length make).
  
  Module Container_result.
    Record signature `{_fargs : FArgs} : Type := {
      Impl : Container.Impl.Impl_signature;
      impl := RocqOfOCaml.OCamlIarray.t Value.(VALUE.t);
      t := impl;
      normalize :
        forall
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Value.(VALUE.t)}
          `{_rocq_assumption_1 :
            RocqOfOCaml.Basics.Unreachable
              (RocqOfOCaml.OCamlIarray.t Value.(VALUE.t))},
          RocqOfOCaml.OCamlIarray.t Value.(VALUE.t) ->
          RocqOfOCaml.OCamlIarray.t Value.(VALUE.t);
      init :
        forall
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Value.(VALUE.t)}
          `{_rocq_assumption_1 :
            RocqOfOCaml.Basics.Unreachable
              (RocqOfOCaml.OCamlIarray.t Value.(VALUE.t))},
          int -> (int -> Value.(VALUE.t)) ->
          RocqOfOCaml.OCamlIarray.t Value.(VALUE.t);
    }.
  End Container_result.
  Definition Container_result `{_fargs : FArgs} := @Container_result.signature _
    _.
  Arguments Container_result {_ _}.
  
  (* Container *)
  Definition functor `{_fargs : FArgs} :@Container_result Value_t _fargs :=
    ((@Container_result.Build_signature Value_t _fargs Impl
      (fun _ _ => normalize) (fun _ _ => init)) :
      @Container_result Value_t _fargs).
End Container.
Definition Container {Value_t : Set} (Value : VALUE (t := Value_t)) :=
  @Container.functor Value_t (Container.Build_FArgs Value).

Module Fixed_string.
  Definition t : Set := string.
  
  Definition init
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
    (make : int -> ascii) : string :=
    let length :=
      if true then
        20
      else
        let '_ := false in
        (@RocqOfOCaml.Basics.unreachable int _) in
    RocqOfOCaml.OCamlString.init length make.
  
  Module Fixed_string_signature.
    Record signature : Type := {
      t := string;
      init :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
          `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int},
          (int -> ascii) -> t;
    }.
  End Fixed_string_signature.
  Definition Fixed_string_signature := Fixed_string_signature.signature.
  
  (* Fixed_string *)
  Definition module :Fixed_string_signature :=
    {|
      Fixed_string_signature.init _ _ := init
    |}.
End Fixed_string.
Definition Fixed_string := Fixed_string.module.

Module Plain_include.
  (** Inclusion of the module [Fixed_string] *)
  Definition t := Fixed_string.(Fixed_string.Fixed_string_signature.t).
  
  Definition init `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable t}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int} :=
    Fixed_string.(Fixed_string.Fixed_string_signature.init) (_rocq_assumption_0
      := _rocq_assumption_0) (_rocq_assumption_1 := _rocq_assumption_1).
  
  Definition zeros
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int} : string :=
    (init (_rocq_assumption_0 := _rocq_assumption_0)
      (_rocq_assumption_1 := _rocq_assumption_1))
      (fun (function_parameter : int) =>
        let '_ := function_parameter in
        "000" % char).
End Plain_include.
