(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition has_even_length {A : Set} (values : list A) : bool :=
  let even :=
  fix even {B : Set} (values : list B) : bool :=
    match values with
    | [] => true
    | Datatypes.cons _ values => odd values
    end
  with odd {B : Set} (values : list B) : bool :=
    match values with
    | [] => false
    | Datatypes.cons _ values => even values
    end
  for even in
  even values.
