(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.
From Stdlib Require Import Program.Wf.

Module DOMAIN.
  Record signature {t : Set} : Type := {
    t := t;
    equal : t -> t -> bool;
    zero : t;
    remainder : t -> t -> t;
  }.
End DOMAIN.
Definition DOMAIN := @DOMAIN.signature.
Arguments DOMAIN {_}.

Module Search.
  Class FArgs {Domain_t : Set} := {
    Domain : DOMAIN (t := Domain_t);
  }.
  Arguments Build_FArgs {_}.
  
  Program Definition run `{_fargs : FArgs}
    (first : Domain.(DOMAIN.t)) (second : Domain.(DOMAIN.t))
    : Domain.(DOMAIN.t) * Domain.(DOMAIN.t) :=
    let _rocq_measure (_rocq_state :
      Domain.(DOMAIN.t) * Domain.(DOMAIN.t) * Domain.(DOMAIN.t) *
        Domain.(DOMAIN.t)) : nat := RocqOfOCaml.Basics.well_founded_measure
      "Search.run.loop" (_fargs, first, second, _rocq_state) in
    let _rocq_body :
      (forall _rocq_state :
        Domain.(DOMAIN.t) * Domain.(DOMAIN.t) * Domain.(DOMAIN.t) *
          Domain.(DOMAIN.t),
        (forall _rocq_next :
          Domain.(DOMAIN.t) * Domain.(DOMAIN.t) * Domain.(DOMAIN.t) *
            Domain.(DOMAIN.t), ltof
          (Domain.(DOMAIN.t) * Domain.(DOMAIN.t) * Domain.(DOMAIN.t) *
            Domain.(DOMAIN.t)) _rocq_measure _rocq_next _rocq_state ->
          Domain.(DOMAIN.t) * Domain.(DOMAIN.t)) ->
        Domain.(DOMAIN.t) * Domain.(DOMAIN.t)) :=
      (fun _rocq_state _rocq_recurse =>
        let '(current, coefficient, next, next_coefficient) := _rocq_state in
        if Domain.(DOMAIN.equal) next Domain.(DOMAIN.zero) then
          (coefficient, current)
        else
          _rocq_recurse
            (next, next_coefficient, (Domain.(DOMAIN.remainder) current next),
              coefficient) _) in
    let _rocq_fix := @Fix
      (Domain.(DOMAIN.t) * Domain.(DOMAIN.t) * Domain.(DOMAIN.t) *
        Domain.(DOMAIN.t)) (ltof
      (Domain.(DOMAIN.t) * Domain.(DOMAIN.t) * Domain.(DOMAIN.t) *
        Domain.(DOMAIN.t)) _rocq_measure) (well_founded_ltof
      (Domain.(DOMAIN.t) * Domain.(DOMAIN.t) * Domain.(DOMAIN.t) *
        Domain.(DOMAIN.t)) _rocq_measure) (fun _ =>
      Domain.(DOMAIN.t) * Domain.(DOMAIN.t)) _rocq_body in
    let loop (current : Domain.(DOMAIN.t)) (coefficient : Domain.(DOMAIN.t))
      (next : Domain.(DOMAIN.t)) (next_coefficient : Domain.(DOMAIN.t)) :
      Domain.(DOMAIN.t) * Domain.(DOMAIN.t) := _rocq_fix (current, coefficient,
      next, next_coefficient) in
    loop first first second second.
  
  Admit Obligations.
  
  Module Search_result.
    Record signature `{_fargs : FArgs} : Type := {
      run :
        Domain.(DOMAIN.t) -> Domain.(DOMAIN.t) ->
        Domain.(DOMAIN.t) * Domain.(DOMAIN.t);
    }.
  End Search_result.
  Definition Search_result `{_fargs : FArgs} := @Search_result.signature _ _.
  Arguments Search_result {_ _}.
  
  (* Search *)
  Definition functor `{_fargs : FArgs} :@Search_result Domain_t _fargs :=
    ((@Search_result.Build_signature Domain_t _fargs run) :
      @Search_result Domain_t _fargs).
End Search.
Definition Search {Domain_t : Set} (Domain : DOMAIN (t := Domain_t)) :=
  @Search.functor Domain_t (Search.Build_FArgs Domain).
