(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module ARGUMENT.
  Record signature : Set := {
    value : int;
  }.
End ARGUMENT.
Definition ARGUMENT := ARGUMENT.signature.

Module Operations.
  Class FArgs := {
    Argument : ARGUMENT;
  }.
  
  Definition get `{_fargs : FArgs} : int := Argument.(ARGUMENT.value).
  
  Definition op_letdollar `{_fargs : FArgs} {A B : Set}
    (value : A) (continuation : A -> B) : B := continuation value.
  
  Module Operations_result.
    Record signature `{_fargs : FArgs} : Set := {
      get : int;
      op_letdollar : forall {A B : Set}, A -> (A -> B) -> B;
    }.
  End Operations_result.
  Definition Operations_result `{_fargs : FArgs} := @Operations_result.signature
    _.
  Arguments Operations_result {_}.
  
  (* Operations *)
  Definition functor `{_fargs : FArgs} :@Operations_result _fargs :=
    ({|
      Operations_result.get (_fargs := _fargs) := (get (_fargs := _fargs));
      Operations_result.op_letdollar (_fargs := _fargs) _ _ :=
        (op_letdollar (_fargs := _fargs))
    |} : @Operations_result _fargs).
End Operations.
Definition Operations (Argument : ARGUMENT) :=
  @Operations.functor (Operations.Build_FArgs Argument).

Module Concrete.
  Definition value : int := 41.
  
  (* Concrete *)
  Definition module :ARGUMENT :=
    {|
      ARGUMENT.value := value
    |}.
End Concrete.
Definition Concrete := Concrete.module.

Definition read (function_parameter : unit) : int :=
  let '_ := function_parameter in
  let opened_module_253 := Operations Concrete in
  opened_module_253.(Operations.Operations_result.op_letdollar)
    opened_module_253.(Operations.Operations_result.get)
    (fun value => Z.add value 1).

Definition read_via_local_module (function_parameter : unit) : int :=
  let '_ := function_parameter in
  let Applied := Operations Concrete in
  Applied.(Operations.Operations_result.get).
