(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition apply {A B : Set} (converter : A -> B) : A -> B :=
  let __0 := converter in
  fun (value : A) => __0 value.

Definition result_value : int := apply (fun (value : int) => Z.add value 1) 41.
