(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition repeat {A : Set} (char : A) (count : int) : list A :=
  RocqOfOCaml.OCamlList.init count
    (fun (function_parameter : int) =>
      let '_ := function_parameter in
      char).
