(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Require Import RocqOfOCaml.ModuleOverrideModel.

Module Counter := RocqOfOCaml.ModuleOverrideModel.

Definition one : RocqOfOCaml.ModuleOverrideModel.t :=
  RocqOfOCaml.ModuleOverrideModel.succ RocqOfOCaml.ModuleOverrideModel.zero.

Definition zero_pred
  `{_rocq_assumption_0 :
    RocqOfOCaml.Basics.Unreachable RocqOfOCaml.ModuleOverrideModel.t} : RocqOfOCaml.ModuleOverrideModel.t :=
  RocqOfOCaml.ModuleOverrideModel.pred RocqOfOCaml.ModuleOverrideModel.zero.

Definition one_as_int : int := RocqOfOCaml.ModuleOverrideModel.to_int one.

Module Nested.
  Definition zero_pred
    `{_rocq_assumption_0 :
      RocqOfOCaml.Basics.Unreachable RocqOfOCaml.ModuleOverrideModel.t} : RocqOfOCaml.ModuleOverrideModel.t :=
    RocqOfOCaml.ModuleOverrideModel.pred RocqOfOCaml.ModuleOverrideModel.zero.
End Nested.
