(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Shared.
  Definition value : int := 7.
End Shared.

Module Shared_alias := Shared.

Module Container.
  Module Shared.
    Definition inherited : int := Shared_alias.value.
  End Shared.
End Container.

Definition result_value : int := Container.Shared.inherited.
