(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Inductive even : Set :=
| Zero : even
| EvenSucc : odd -> even

with odd : Set :=
| OddSucc : even -> odd.

Fixpoint even_to_int
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
  (function_parameter : even) : int :=
  match function_parameter with
  | Zero => 0
  | EvenSucc value => odd_to_int value
  end

with odd_to_int
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
  (function_parameter : odd) : int :=
  let 'OddSucc value := function_parameter in
  let '_ :=
    if RocqOfOCaml.Basics.Stdlib.ge (even_to_int value) 0 then tt else
      (@RocqOfOCaml.Basics.unreachable unit _) in
  1.
