(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module FIELD.
  Record signature {t : Set} : Type := {
    t := t;
    zero : t;
  }.
End FIELD.
Definition FIELD := @FIELD.signature.
Arguments FIELD {_}.

Module Use_M_signature.
  Record signature : Type := {
    Field_t := int;
    Field_zero : Field_t;
    Field_one : Field_t;
    Wrapped_t := Field_t;
    Wrapped_make : Field_t -> Wrapped_t;
  }.
End Use_M_signature.
Definition Use_M_signature := Use_M_signature.signature.

Module Use.
  Class FArgs := {
    M : Use_M_signature;
  }.
  
  Definition zero `{_fargs : FArgs} : int := M.(Use_M_signature.Field_zero).
  
  Definition one `{_fargs : FArgs} : int := M.(Use_M_signature.Field_one).
  
  Definition wrapped `{_fargs : FArgs} : int :=
    M.(Use_M_signature.Wrapped_make) one.
  
  Module Use_result.
    Record signature `{_fargs : FArgs} : Type := {
      zero : int;
      one : int;
      wrapped : int;
    }.
  End Use_result.
  Definition Use_result `{_fargs : FArgs} := @Use_result.signature _.
  Arguments Use_result {_}.
  
  (* Use *)
  Definition functor `{_fargs : FArgs} :@Use_result _fargs :=
    ((@Use_result.Build_signature _fargs zero one wrapped) : @Use_result _fargs).
End Use.
Definition Use (M : Use_M_signature) := @Use.functor (Use.Build_FArgs M).
