(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Base.
  Module Inner.
    Class FArgs {Value_t : Set} := {
      Value : RocqOfOCaml.OCamlSet.OrderedType (t := Value_t);
    }.
    Arguments Build_FArgs {_}.
    
    Inductive t `{_fargs : FArgs} (a : Set) : Set :=
    | Wrap : Value.(RocqOfOCaml.OCamlMap.OrderedType.t) -> a -> t a.
    
    Arguments Wrap {_ _ _}.
    
    Definition make `{_fargs : FArgs} {A : Set}
      (value : Value.(RocqOfOCaml.OCamlMap.OrderedType.t)) (payload : A)
      : t A := Wrap value payload.
    
    Module Inner_result.
      Record signature `{_fargs : FArgs} {t : Set -> Set} : Set := {
        t := t;
        make :
          forall {A : Set} ,
            Value.(RocqOfOCaml.OCamlMap.OrderedType.t) -> A -> t A;
      }.
    End Inner_result.
    Definition Inner_result `{_fargs : FArgs} := @Inner_result.signature _ _.
    Arguments Inner_result {_ _ _}.
    
    (* Inner *)
    Definition functor `{_fargs : FArgs} :Inner_result (t := _) :=
      {|
        Inner_result.make _ := (make (_fargs := _fargs))
      |}.
  End Inner.
  Definition Inner {Value_t : Set}
    (Value : RocqOfOCaml.OCamlSet.OrderedType (t := Value_t)) :=
    @Inner.functor Value_t (Inner.Build_FArgs Value).
  
  Module Wrapped.
    Class FArgs {Value_t : Set} := {
      Value : RocqOfOCaml.OCamlSet.OrderedType (t := Value_t);
    }.
    Arguments Build_FArgs {_}.
    
    Definition Inner_include_fargs `{_fargs : FArgs} := Inner.Build_FArgs Value.
    
    Definition Inner_include `{_fargs : FArgs} :
      Inner.Inner_result (_fargs := Inner_include_fargs) := Inner Value.
    
    (** Inclusion of the module [Inner_include] *)
    Definition t `{_fargs : FArgs} (a : Set) :=
      Inner_include.(Inner.Inner_result.t) a.
    
    Definition make `{_fargs : FArgs} {A : Set} :
      Value.(RocqOfOCaml.OCamlMap.OrderedType.t) -> A -> t A :=
      Inner_include.(Inner.Inner_result.make).
    
    Module Wrapped_result.
      Record signature `{_fargs : FArgs} {t : Set -> Set} : Set := {
        t := t;
        make :
          forall {A : Set} ,
            Value.(RocqOfOCaml.OCamlMap.OrderedType.t) -> A -> t A;
      }.
    End Wrapped_result.
    Definition Wrapped_result `{_fargs : FArgs} := @Wrapped_result.signature _
      _.
    Arguments Wrapped_result {_ _ _}.
    
    (* Wrapped *)
    Definition functor `{_fargs : FArgs} :Wrapped_result (t := _) :=
      {|
        Wrapped_result.make _ := (make (_fargs := _fargs))
      |}.
  End Wrapped.
  Definition Wrapped {Value_t : Set}
    (Value : RocqOfOCaml.OCamlSet.OrderedType (t := Value_t)) :=
    @Wrapped.functor Value_t (Wrapped.Build_FArgs Value).
End Base.

Module Outer.
  Class FArgs {Value_t : Set} := {
    Value : RocqOfOCaml.OCamlSet.OrderedType (t := Value_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module Nested.
    Definition Base_Wrapped_include `{_fargs : FArgs} := Base.Wrapped Value.
    
    (** Inclusion of the module [Base_Wrapped_include] *)
    Definition t `{_fargs : FArgs} (a : Set) :=
      Base_Wrapped_include.(Base.Wrapped.Wrapped_result.t) a.
    
    Definition make `{_fargs : FArgs} {A : Set} :
      Value.(RocqOfOCaml.OCamlMap.OrderedType.t) -> A -> t A :=
      Base_Wrapped_include.(Base.Wrapped.Wrapped_result.make).
    
    Definition duplicate `{_fargs : FArgs} {A : Set}
      (value : Value.(RocqOfOCaml.OCamlMap.OrderedType.t)) (payload : A)
      : t A * t A := ((make value payload), (make value payload)).
  End Nested.
  
  Module Outer_result.
    Record signature `{_fargs : FArgs} {Nested_t : Set -> Set} : Set := {
      Nested_t := Nested_t;
      Nested_make :
        forall {A : Set} ,
          Value.(RocqOfOCaml.OCamlMap.OrderedType.t) -> A -> Nested_t A;
      Nested_duplicate :
        forall {A : Set} ,
          Value.(RocqOfOCaml.OCamlMap.OrderedType.t) -> A ->
          Nested_t A * Nested_t A;
    }.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _ _.
  Arguments Outer_result {_ _ _}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :Outer_result (Nested_t := _) :=
    {|
      Outer_result.Nested_make _ := (Nested.make (_fargs := _fargs));
      Outer_result.Nested_duplicate _ := (Nested.duplicate (_fargs := _fargs))
    |}.
End Outer.
Definition Outer {Value_t : Set}
  (Value : RocqOfOCaml.OCamlSet.OrderedType (t := Value_t)) :=
  @Outer.functor Value_t (Outer.Build_FArgs Value).
