(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module TOKEN.
  Record signature : Set := {
    token : unit;
  }.
End TOKEN.
Definition TOKEN := TOKEN.signature.

Module Number.
  Class FArgs := {
    Token : TOKEN;
  }.
  
  Module Impl.
    Definition t `{_fargs : FArgs} : Set := int.
    
    Definition make `{_fargs : FArgs} {A : Set} (value : A) : A := value.
    
    Module Impl_signature.
      Record signature `{_fargs : FArgs} {t : Set} : Set := {
        t := t;
        make : int -> t;
      }.
    End Impl_signature.
    Definition Impl_signature `{_fargs : FArgs} := @Impl_signature.signature _.
    Arguments Impl_signature {_ _}.
    
    (* Impl *)
    Definition module `{_fargs : FArgs} :Impl_signature (t := _) :=
      {|
        Impl_signature.make := make
      |}.
  End Impl.
  Definition Impl `{_fargs : FArgs} := Impl.module.
  
  (** Inclusion of the module [Impl] *)
  Definition t `{_fargs : FArgs} := Impl.(Impl.Impl_signature.t).
  
  Definition make `{_fargs : FArgs} : int -> t :=
    Impl.(Impl.Impl_signature.make).
  
  Definition _Set `{_fargs : FArgs} :=
    RocqOfOCaml.OCamlSet.Make
      (let t : Set := Impl.(Impl.Impl_signature.t) in
      let compare (function_parameter : t) : t -> int :=
        let '_ := function_parameter in
        fun (function_parameter : t) =>
          let '_ := function_parameter in
          0 in
      ({|
        RocqOfOCaml.OCamlMap.OrderedType.compare := compare
      |} : RocqOfOCaml.OCamlMap.OrderedType (t := t))).
  
  Module Number_result.
    Record signature `{_fargs : FArgs} {Impl_t Set_t : Set} : Set := {
      Impl : Number.Impl.Impl_signature (t := Impl_t);
      t := Impl_t;
      make : int -> Impl_t;
      _Set : RocqOfOCaml.OCamlSet.S (elt := Impl_t) (t := Set_t);
    }.
  End Number_result.
  Definition Number_result `{_fargs : FArgs} := @Number_result.signature _.
  Arguments Number_result {_ _ _}.
  
  (* Number *)
  Definition functor `{_fargs : FArgs} :Number_result (Impl_t := _) (Set_t := _)
    :=
    {|
      Number_result.Impl := (Impl (_fargs := _fargs));
      Number_result.make := (make (_fargs := _fargs));
      Number_result._Set := (_Set (_fargs := _fargs))
    |}.
End Number.
Definition Number (Token : TOKEN) := @Number.functor (Number.Build_FArgs Token).

Module Representation.
  Class FArgs := {
    Token : TOKEN;
  }.
  
  Module Impl.
    Definition t `{_fargs : FArgs} : Set := string.
    
    Definition make `{_fargs : FArgs} {A : Set} (value : A) : A := value.
    
    Module Impl_signature.
      Record signature `{_fargs : FArgs} {t : Set} : Set := {
        t := t;
        make : string -> t;
      }.
    End Impl_signature.
    Definition Impl_signature `{_fargs : FArgs} := @Impl_signature.signature _.
    Arguments Impl_signature {_ _}.
    
    (* Impl *)
    Definition module `{_fargs : FArgs} :Impl_signature (t := _) :=
      {|
        Impl_signature.make := make
      |}.
  End Impl.
  Definition Impl `{_fargs : FArgs} := Impl.module.
  
  (** Inclusion of the module [Impl] *)
  Definition t `{_fargs : FArgs} := Impl.(Impl.Impl_signature.t).
  
  Definition make `{_fargs : FArgs} : string -> t :=
    Impl.(Impl.Impl_signature.make).
  
  Definition bytes_marker `{_fargs : FArgs} : unit := tt.
  
  Module Representation_result.
    Record signature `{_fargs : FArgs} {Impl_t : Set} : Set := {
      Impl : Representation.Impl.Impl_signature (t := Impl_t);
      t := Impl_t;
      make : string -> Impl_t;
      bytes_marker : unit;
    }.
  End Representation_result.
  Definition Representation_result `{_fargs : FArgs} :=
    @Representation_result.signature _.
  Arguments Representation_result {_ _}.
  
  (* Representation *)
  Definition functor `{_fargs : FArgs} :Representation_result (Impl_t := _) :=
    {|
      Representation_result.Impl := (Impl (_fargs := _fargs));
      Representation_result.make := (make (_fargs := _fargs));
      Representation_result.bytes_marker := (bytes_marker (_fargs := _fargs))
    |}.
End Representation.
Definition Representation (Token : TOKEN) :=
  @Representation.functor (Representation.Build_FArgs Token).

Module ConcreteRepresentation.
  Class FArgs := {
    Token : TOKEN;
  }.
  
  Module Impl.
    Definition t `{_fargs : FArgs} : Set := string.
    
    Definition make `{_fargs : FArgs} {A : Set} (value : A) : A := value.
    
    Module Impl_signature.
      Record signature `{_fargs : FArgs} : Set := {
        t := string;
        make : string -> t;
      }.
    End Impl_signature.
    Definition Impl_signature `{_fargs : FArgs} := @Impl_signature.signature _.
    Arguments Impl_signature {_}.
    
    (* Impl *)
    Definition module `{_fargs : FArgs} :Impl_signature :=
      {|
        Impl_signature.make := make
      |}.
  End Impl.
  Definition Impl `{_fargs : FArgs} := Impl.module.
  
  (** Inclusion of the module [Impl] *)
  Definition t `{_fargs : FArgs} := Impl.(Impl.Impl_signature.t).
  
  Definition make `{_fargs : FArgs} : t -> Impl.(Impl.Impl_signature.t) :=
    Impl.(Impl.Impl_signature.make).
  
  Module ConcreteRepresentation_result.
    Record signature `{_fargs : FArgs} : Set := {
      Impl : ConcreteRepresentation.Impl.Impl_signature;
      t := string;
      make : string -> string;
    }.
  End ConcreteRepresentation_result.
  Definition ConcreteRepresentation_result `{_fargs : FArgs} :=
    @ConcreteRepresentation_result.signature _.
  Arguments ConcreteRepresentation_result {_}.
  
  (* ConcreteRepresentation *)
  Definition functor `{_fargs : FArgs} :@ConcreteRepresentation_result _fargs :=
    ({|
      ConcreteRepresentation_result.Impl (_fargs := _fargs) :=
        (Impl (_fargs := _fargs));
      ConcreteRepresentation_result.make (_fargs := _fargs) :=
        (make (_fargs := _fargs))
    |} : @ConcreteRepresentation_result _fargs).
End ConcreteRepresentation.
Definition ConcreteRepresentation (Token : TOKEN) :=
  @ConcreteRepresentation.functor (ConcreteRepresentation.Build_FArgs Token).

Module Pair.
  Class FArgs := {
    Token : TOKEN;
  }.
  
  Definition S_fargs `{_fargs : FArgs} := Number.Build_FArgs Token.
  
  Definition S `{_fargs : FArgs} : Number.Number_result (_fargs := S_fargs) :=
    Number Token.
  
  Module Signed.
    (** Inclusion of the module [S] *)
    Module Impl.
      Definition t `{_fargs : FArgs} :=
        S.(Number.Number_result.Impl).(Number.Impl.Impl_signature.t).
      
      Definition make `{_fargs : FArgs} : int -> t :=
        S.(Number.Number_result.Impl).(Number.Impl.Impl_signature.make).
    End Impl.
    
    Definition Impl `{_fargs : FArgs} := S.(Number.Number_result.Impl).
    
    Definition t `{_fargs : FArgs} := S.(Number.Number_result.t).
    
    Definition make `{_fargs : FArgs} : int -> t :=
      S.(Number.Number_result.make).
    
    Module _Set.
      Definition elt `{_fargs : FArgs} :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.elt).
      
      Definition t `{_fargs : FArgs} :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.t).
      
      Definition empty `{_fargs : FArgs} : t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.empty).
      
      Definition add `{_fargs : FArgs} : elt -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.add).
      
      Definition singleton `{_fargs : FArgs} : elt -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.singleton).
      
      Definition remove `{_fargs : FArgs} : elt -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.remove).
      
      Definition union `{_fargs : FArgs} : t -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.union).
      
      Definition inter `{_fargs : FArgs} : t -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.inter).
      
      Definition disjoint `{_fargs : FArgs} : t -> t -> bool :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.disjoint).
      
      Definition diff `{_fargs : FArgs} : t -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.diff).
      
      Definition cardinal `{_fargs : FArgs} : t -> int :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.cardinal).
      
      Definition elements `{_fargs : FArgs} : t -> list elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.elements).
      
      Definition min_elt `{_fargs : FArgs} : t -> elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.min_elt).
      
      Definition min_elt_opt `{_fargs : FArgs} : t -> option elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.min_elt_opt).
      
      Definition max_elt `{_fargs : FArgs} : t -> elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.max_elt).
      
      Definition max_elt_opt `{_fargs : FArgs} : t -> option elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.max_elt_opt).
      
      Definition choose `{_fargs : FArgs} : t -> elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.choose).
      
      Definition choose_opt `{_fargs : FArgs} : t -> option elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.choose_opt).
      
      Definition find `{_fargs : FArgs} : elt -> t -> elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.find).
      
      Definition find_opt `{_fargs : FArgs} : elt -> t -> option elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.find_opt).
      
      Definition find_first `{_fargs : FArgs} : (elt -> bool) -> t -> elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.find_first).
      
      Definition find_first_opt `{_fargs : FArgs} :
        (elt -> bool) -> t -> option elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.find_first_opt).
      
      Definition find_last `{_fargs : FArgs} : (elt -> bool) -> t -> elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.find_last).
      
      Definition find_last_opt `{_fargs : FArgs} :
        (elt -> bool) -> t -> option elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.find_last_opt).
      
      Definition iter `{_fargs : FArgs} : (elt -> unit) -> t -> unit :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.iter).
      
      Definition fold `{_fargs : FArgs} {acc : Set} :
        (elt -> acc -> acc) -> t -> acc -> acc :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.fold).
      
      Definition map `{_fargs : FArgs} : (elt -> elt) -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.map).
      
      Definition filter `{_fargs : FArgs} : (elt -> bool) -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.filter).
      
      Definition filter_map `{_fargs : FArgs} : (elt -> option elt) -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.filter_map).
      
      Definition partition `{_fargs : FArgs} : (elt -> bool) -> t -> t * t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.partition).
      
      Definition split `{_fargs : FArgs} : elt -> t -> t * bool * t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.split).
      
      Definition is_empty `{_fargs : FArgs} : t -> bool :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.is_empty).
      
      Definition mem `{_fargs : FArgs} : elt -> t -> bool :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.mem).
      
      Definition equal `{_fargs : FArgs} : t -> t -> bool :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.equal).
      
      Definition compare `{_fargs : FArgs} : t -> t -> int :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.compare).
      
      Definition subset `{_fargs : FArgs} : t -> t -> bool :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.subset).
      
      Definition for_all `{_fargs : FArgs} : (elt -> bool) -> t -> bool :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.for_all).
      
      Definition _exists `{_fargs : FArgs} : (elt -> bool) -> t -> bool :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S._exists).
      
      Definition to_list `{_fargs : FArgs} : t -> list elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.to_list).
      
      Definition of_list `{_fargs : FArgs} : list elt -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.of_list).
      
      Definition to_seq_from `{_fargs : FArgs} :
        elt -> t -> RocqOfOCaml.OCamlSeq.t elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.to_seq_from).
      
      Definition to_seq `{_fargs : FArgs} : t -> RocqOfOCaml.OCamlSeq.t elt :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.to_seq).
      
      Definition to_rev_seq `{_fargs : FArgs} : t -> RocqOfOCaml.OCamlSeq.t elt
        := S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.to_rev_seq).
      
      Definition add_seq `{_fargs : FArgs} :
        RocqOfOCaml.OCamlSeq.t elt -> t -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.add_seq).
      
      Definition of_seq `{_fargs : FArgs} : RocqOfOCaml.OCamlSeq.t elt -> t :=
        S.(Number.Number_result._Set).(RocqOfOCaml.OCamlSet.S.of_seq).
    End _Set.
    
    Definition _Set `{_fargs : FArgs} := S.(Number.Number_result._Set).
    
    Definition Repr_fargs `{_fargs : FArgs} := Representation.Build_FArgs Token.
    
    Definition Repr `{_fargs : FArgs} :
      Representation.Representation_result (_fargs := Repr_fargs) :=
      Representation Token.
    
    Definition Bytes_fargs `{_fargs : FArgs} :=
      ConcreteRepresentation.Build_FArgs Token.
    
    Definition Bytes `{_fargs : FArgs} :
      ConcreteRepresentation.ConcreteRepresentation_result
        (_fargs := Bytes_fargs) := ConcreteRepresentation Token.
    
    Definition of_repr `{_fargs : FArgs}
      (function_parameter : Repr.(Representation.Representation_result.t))
      : S.(Number.Number_result.t) :=
      let '_ := function_parameter in
      S.(Number.Number_result.make) 0.
    
    Definition of_bytes `{_fargs : FArgs} (function_parameter : string)
      : S.(Number.Number_result.t) :=
      let '_ := function_parameter in
      S.(Number.Number_result.make) 0.
  End Signed.
  
  Module Pair_result.
    Record signature `{_fargs : FArgs}
      {S_Impl_t S_Set_t Signed_Repr_Impl_t : Set} : Set := {
      S :
        Number.Number_result (_fargs := S_fargs) (Impl_t := S_Impl_t)
          (Set_t := S_Set_t);
      Signed_Impl_t := S_Impl_t;
      Signed_Impl_make : int -> S_Impl_t;
      Signed_t := S_Impl_t;
      Signed_make : int -> S_Impl_t;
      Signed_Set_t := S_Set_t;
      Signed_Set : RocqOfOCaml.OCamlSet.S (elt := S_Impl_t) (t := S_Set_t);
      Signed_Repr :
        Representation.Representation_result (_fargs := Signed.Repr_fargs)
          (Impl_t := Signed_Repr_Impl_t);
      Signed_Bytes :
        ConcreteRepresentation.ConcreteRepresentation_result
          (_fargs := Signed.Bytes_fargs);
      Signed_of_repr : Signed_Repr_Impl_t -> S_Impl_t;
      Signed_of_bytes : string -> S_Impl_t;
    }.
  End Pair_result.
  Definition Pair_result `{_fargs : FArgs} := @Pair_result.signature _.
  Arguments Pair_result {_ _ _ _}.
  
  (* Pair *)
  Definition functor `{_fargs : FArgs}
    :Pair_result (S_Impl_t := _) (S_Set_t := _) (Signed_Repr_Impl_t := _) :=
    {|
      Pair_result.S := (S (_fargs := _fargs));
      Pair_result.Signed_Impl_make := (Signed.Impl.make (_fargs := _fargs));
      Pair_result.Signed_make := (Signed.make (_fargs := _fargs));
      Pair_result.Signed_Set := Signed._Set;
      Pair_result.Signed_Repr := (Signed.Repr (_fargs := _fargs));
      Pair_result.Signed_Bytes := (Signed.Bytes (_fargs := _fargs));
      Pair_result.Signed_of_repr := (Signed.of_repr (_fargs := _fargs));
      Pair_result.Signed_of_bytes := (Signed.of_bytes (_fargs := _fargs))
    |}.
End Pair.
Definition Pair (Token : TOKEN) := @Pair.functor (Pair.Build_FArgs Token).
