(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module ARGUMENT.
  Record signature : Set := {
    token : unit;
  }.
End ARGUMENT.
Definition ARGUMENT := ARGUMENT.signature.

Module Make.
  Class FArgs := {
    Argument : ARGUMENT;
  }.
  
  Module Impl.
    Definition t `{_fargs : FArgs} : Set := int.
    
    Definition make `{_fargs : FArgs} {A : Set} (value : A) : A := value.
    
    Module Impl_signature.
      Record signature `{_fargs : FArgs} {t : Set} : Set := {
        t := t;
        make : int -> t;
      }.
    End Impl_signature.
    Definition Impl_signature `{_fargs : FArgs} := @Impl_signature.signature _.
    Arguments Impl_signature {_ _}.
    
    (* Impl *)
    Definition module `{_fargs : FArgs} :Impl_signature (t := _) :=
      {|
        Impl_signature.make := make
      |}.
  End Impl.
  Definition Impl `{_fargs : FArgs} := Impl.module.
  
  (** Inclusion of the module [Impl] *)
  Definition t `{_fargs : FArgs} := Impl.(Impl.Impl_signature.t).
  
  Definition make `{_fargs : FArgs} : int -> t :=
    Impl.(Impl.Impl_signature.make).
  
  Definition identity `{_fargs : FArgs} (value : Impl.(Impl.Impl_signature.t))
    : Impl.(Impl.Impl_signature.t) := value.
  
  Module Make_result.
    Record signature `{_fargs : FArgs} {Impl_t : Set} : Set := {
      Impl : Make.Impl.Impl_signature (t := Impl_t);
      t := Impl_t;
      make : int -> Impl_t;
      identity : Impl_t -> Impl_t;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_ _}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :Make_result (Impl_t := _) :=
    {|
      Make_result.Impl := (Impl (_fargs := _fargs));
      Make_result.make := (make (_fargs := _fargs));
      Make_result.identity := (identity (_fargs := _fargs))
    |}.
End Make.
Definition Make (Argument : ARGUMENT) :=
  @Make.functor (Make.Build_FArgs Argument).

Module Outer.
  Class FArgs := {
    Argument : ARGUMENT;
  }.
  
  Definition S_fargs `{_fargs : FArgs} := Make.Build_FArgs Argument.
  
  Definition S `{_fargs : FArgs} : Make.Make_result (_fargs := S_fargs) :=
    Make Argument.
  
  Module Signed.
    (** Inclusion of the module [S] *)
    Module Impl.
      Definition t `{_fargs : FArgs} :=
        S.(Make.Make_result.Impl).(Make.Impl.Impl_signature.t).
      
      Definition make `{_fargs : FArgs} : int -> t :=
        S.(Make.Make_result.Impl).(Make.Impl.Impl_signature.make).
    End Impl.
    
    Definition Impl `{_fargs : FArgs} := S.(Make.Make_result.Impl).
    
    Definition t `{_fargs : FArgs} := S.(Make.Make_result.t).
    
    Definition make `{_fargs : FArgs} : int -> t := S.(Make.Make_result.make).
    
    Definition identity `{_fargs : FArgs} : t -> t :=
      S.(Make.Make_result.identity).
    
    Definition round_trip `{_fargs : FArgs} (value : int)
      : S.(Make.Make_result.t) := identity (make value).
  End Signed.
  
  Module Outer_result.
    Record signature `{_fargs : FArgs} {S_Impl_t : Set} : Set := {
      S : Make.Make_result (_fargs := S_fargs) (Impl_t := S_Impl_t);
      Signed_Impl_t := S_Impl_t;
      Signed_Impl_make : int -> S_Impl_t;
      Signed_t := S_Impl_t;
      Signed_make : int -> S_Impl_t;
      Signed_identity : S_Impl_t -> S_Impl_t;
      Signed_round_trip : int -> S_Impl_t;
    }.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _.
  Arguments Outer_result {_ _}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :Outer_result (S_Impl_t := _) :=
    {|
      Outer_result.S := (S (_fargs := _fargs));
      Outer_result.Signed_Impl_make := (Signed.Impl.make (_fargs := _fargs));
      Outer_result.Signed_make := (Signed.make (_fargs := _fargs));
      Outer_result.Signed_identity := (Signed.identity (_fargs := _fargs));
      Outer_result.Signed_round_trip := (Signed.round_trip (_fargs := _fargs))
    |}.
End Outer.
Definition Outer (Argument : ARGUMENT) :=
  @Outer.functor (Outer.Build_FArgs Argument).

Module Argument.
  Definition token : unit := tt.
  
  (* Argument *)
  Definition module :ARGUMENT :=
    {|
      ARGUMENT.token := token
    |}.
End Argument.
Definition Argument := Argument.module.

Definition Result_fargs := Outer.Build_FArgs Argument.

Definition Result : Outer.Outer_result (_fargs := Result_fargs) :=
  Outer Argument.

Definition make_through_alias
  : int -> Result.(Outer.Outer_result.Signed_Impl_t) :=
  Result.(Outer.Outer_result.Signed_Impl_make).
