(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module F_X_signature.
  Record signature : Type := {
    value : int;
  }.
End F_X_signature.
Definition F_X_signature := F_X_signature.signature.

Module F.
  Class FArgs := {
    X : F_X_signature;
  }.

  Module Impl.
    Definition t `{_fargs : FArgs} : Set := int.

    Definition value `{_fargs : FArgs} : int := X.(F_X_signature.value).

    Module Impl_signature.
      Record signature `{_fargs : FArgs} : Type := {
        t := int;
        value : t;
      }.
    End Impl_signature.
    Definition Impl_signature `{_fargs : FArgs} := @Impl_signature.signature _.
    Arguments Impl_signature {_}.

    (* Impl *)
    Definition module `{_fargs : FArgs} :Impl_signature :=
      {|
        Impl_signature.value := value
      |}.
  End Impl.
  Definition Impl `{_fargs : FArgs} := Impl.module.

  (** Inclusion of the module [Impl] *)
  Definition t `{_fargs : FArgs} := Impl.(Impl.Impl_signature.t).

  Definition value `{_fargs : FArgs} : t := Impl.(Impl.Impl_signature.value).

  Module F_result.
    Record signature `{_fargs : FArgs} : Type := {
      Impl : F.Impl.Impl_signature;
      t := int;
      value : int;
    }.
  End F_result.
  Definition F_result `{_fargs : FArgs} := @F_result.signature _.
  Arguments F_result {_}.

  (* F *)
  Definition functor `{_fargs : FArgs} :@F_result _fargs :=
    ((@F_result.Build_signature _fargs Impl value) : @F_result _fargs).
End F.
Definition F (X : F_X_signature) := @F.functor (F.Build_FArgs X).

Module Applied.
  Definition F_include_fargs :=
    F.Build_FArgs
      (let value := 7 in
      ({|
        F_X_signature.value := value
      |} : F_X_signature)).

  Definition F_include : F.F_result (_fargs := F_include_fargs) :=
    F
      (let value := 7 in
      ({|
        F_X_signature.value := value
      |} : F_X_signature)).

  (** Inclusion of the module [F_include] *)
  Module Impl.
    Definition t := F_include.(F.F_result.Impl).(F.Impl.Impl_signature.t).

    Definition value : t :=
      F_include.(F.F_result.Impl).(F.Impl.Impl_signature.value).
  End Impl.

  Definition Impl := F_include.(F.F_result.Impl).

  Definition t := F_include.(F.F_result.t).

  Definition value : t := F_include.(F.F_result.value).
End Applied.
