(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Outer_T_signature.
  Record signature {t : Set} : Type := {
    t := t;
  }.
End Outer_T_signature.
Definition Outer_T_signature := @Outer_T_signature.signature.
Arguments Outer_T_signature {_}.

Module Outer.
  Class FArgs {T_t : Set} := {
    T : Outer_T_signature (t := T_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module SIG.
    Record signature `{_fargs : FArgs} : Type := {
      get : T.(Outer_T_signature.t);
    }.
  End SIG.
  Definition SIG `{_fargs : FArgs} := @SIG.signature _ _.
  Arguments SIG {_ _}.
  
  Module Copy.
    Class FArgs `{_fargs : FArgs} := {
      M : SIG;
    }.
    Arguments Build_FArgs {_ _}.
    
    Definition get `{_fargs : FArgs} : T.(Outer_T_signature.t) :=
      (M (FArgs := _fargs)).(SIG.get).
    
    (* Copy *)
    Definition functor `{_fargs : FArgs} :SIG :=
      {|
        SIG.get := get
      |}.
  End Copy.
  Definition Copy `{_fargs : FArgs} (M : SIG) :=
    @Copy.functor _ _ (Copy.Build_FArgs M).
  
  Module Outer_result.
    Inductive signature `{_fargs : FArgs} : Type :=
    | Build_signature : signature.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _ _.
  Arguments Outer_result {_ _}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :@Outer_result T_t _fargs :=
    ((@Outer_result.Build_signature T_t _fargs) : @Outer_result T_t _fargs).
End Outer.
Definition Outer {T_t : Set} (T : Outer_T_signature (t := T_t)) :=
  @Outer.functor T_t (Outer.Build_FArgs T).
