(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Option.
  Definition t (a : Set) : Set := option a.
  
  Definition none {A : Set} : option A := None.
  
  Definition _return {A : Set} (value : A) : option A := Some value.
End Option.

Module Make_Token_signature.
  Record signature : Set := {
    token : unit;
  }.
End Make_Token_signature.
Definition Make_Token_signature := Make_Token_signature.signature.

Module Make.
  Class FArgs := {
    Token : Make_Token_signature;
  }.
  
  Module Option.
    Include Option.
  End Option.
  
  Module Make_result.
    Record signature `{_fargs : FArgs} : Set := {
      Option_t := fun (a : Set) => option a;
      Option_none : forall {A : Set} , option A;
      Option_return : forall {A : Set} , A -> option A;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result _fargs :=
    ({|
      Make_result.Option_none (_fargs := _fargs) _ := Option.none;
      Make_result.Option_return (_fargs := _fargs) _ := Option._return
    |} : @Make_result _fargs).
End Make.
Definition Make (Token : Make_Token_signature) :=
  @Make.functor (Make.Build_FArgs Token).

Module Token.
  Definition token : unit := tt.
End Token.

Module Result.
  Definition Make_include_fargs :=
    Make.Build_FArgs
      ({|
        Make_Token_signature.token := Token.token
      |} : Make_Token_signature).
  
  Definition Make_include : Make.Make_result (_fargs := Make_include_fargs) :=
    Make
      ({|
        Make_Token_signature.token := Token.token
      |} : Make_Token_signature).
  
  (** Inclusion of the module [Make_include] *)
  Module Option.
    Definition t (a : Set) := Make_include.(Make.Make_result.Option_t) a.
    
    Definition none {A : Set} : Make_include.(Make.Make_result.Option_t) A :=
      Make_include.(Make.Make_result.Option_none).
    
    Definition _return {A : Set} :
      A -> Make_include.(Make.Make_result.Option_t) A :=
      Make_include.(Make.Make_result.Option_return).
  End Option.
End Result.
