(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module MONAD.
  Record signature {t : Set -> Set} : Set := {
    t := t;
    _return : forall {a : Set} , a -> t a;
    bind : forall {a b : Set} , t a -> (a -> t b) -> t b;
  }.
End MONAD.
Definition MONAD := @MONAD.signature.
Arguments MONAD {_}.

Module Make.
  Class FArgs {M_t : Set -> Set} := {
    M : MONAD (t := M_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module Seq.
    CoFixpoint sequence `{_fargs : FArgs} {A : Set}
      (values : RocqOfOCaml.OCamlSeq.t (M.(MONAD.t) A))
      : RocqOfOCaml.Partial.Resumption.t M.(MONAD.t) (RocqOfOCaml.OCamlSeq.t A) :=
      (RocqOfOCaml.Partial.Resumption.Tau (M := M.(MONAD.t)))
        (fun _ =>
          match values tt with
          | RocqOfOCaml.OCamlSeq.Nil =>
            (RocqOfOCaml.Partial.Resumption.Done (M := M.(MONAD.t)))
              RocqOfOCaml.OCamlSeq.empty
          | RocqOfOCaml.OCamlSeq.Cons value rest =>
            (RocqOfOCaml.Partial.Resumption.Bind (M := M.(MONAD.t))) value
              (fun (value : A) =>
                (RocqOfOCaml.Partial.Resumption.Compose (M := M.(MONAD.t)))
                  ((RocqOfOCaml.Partial.Resumption.Tau (M := M.(MONAD.t)))
                    (fun _ => sequence rest))
                  (fun (rest : RocqOfOCaml.OCamlSeq.t A) =>
                    (RocqOfOCaml.Partial.Resumption.Done (M := M.(MONAD.t)))
                      (RocqOfOCaml.OCamlSeq.cons value rest)))
          end).
  End Seq.
  
  Module Make_result.
    Record signature `{_fargs : FArgs} : Set := {
      Seq_sequence :
        forall {A : Set} ,
          RocqOfOCaml.OCamlSeq.t (M.(MONAD.t) A) ->
          RocqOfOCaml.Partial.Resumption.t M.(MONAD.t)
            (RocqOfOCaml.OCamlSeq.t A);
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _ _.
  Arguments Make_result {_ _}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result M_t _fargs :=
    ({|
      Make_result.Seq_sequence (M_t := M_t) (_fargs := _fargs) _ :=
        (Seq.sequence (_fargs := _fargs))
    |} : @Make_result M_t _fargs).
End Make.
Definition Make {M_t : Set -> Set} (M : MONAD (t := M_t)) :=
  @Make.functor M_t (Make.Build_FArgs M).

Module Identity.
  Definition t (a : Set) : Set := a.
  
  Definition _return {A : Set} (value : A) : A := value.
  
  Definition bind {A B : Set} (value : A) (body : A -> B) : B := body value.
  
  (* Identity *)
  Definition module :MONAD (t := fun (a : Set) => a) :=
    {|
      MONAD._return _ := _return;
      MONAD.bind _ _ := bind
    |}.
End Identity.
Definition Identity := Identity.module.

Module State_T_signature.
  Record signature {t : Set} : Set := {
    t := t;
  }.
End State_T_signature.
Definition State_T_signature := @State_T_signature.signature.
Arguments State_T_signature {_}.

Module State.
  Class FArgs {T_t : Set} {Inner_t : Set -> Set} := {
    T : State_T_signature (t := T_t);
    Inner_parameter : MONAD (t := Inner_t);
  }.
  Arguments Build_FArgs {_ _}.
  
  Definition state `{_fargs : FArgs} : Set := T.(State_T_signature.t).
  
  Definition Inner `{_fargs : FArgs} := Inner_parameter.
  
  Module M.
    Definition t `{_fargs : FArgs} (a : Set) : Set :=
      state -> Inner.(MONAD.t) (a * state).
    
    Definition _return `{_fargs : FArgs} {A B : Set} (value : A) (state : B)
      : Inner.(MONAD.t) (A * B) :=
      (Inner.(MONAD._return) (a := A * B)) (value, state).
    
    Definition bind `{_fargs : FArgs} {A B C D : Set}
      (computation : A -> Inner.(MONAD.t) (B * C))
      (body : B -> C -> Inner.(MONAD.t) D) (state : A) : Inner.(MONAD.t) D :=
      (Inner.(MONAD.bind) (b := D) (a := B * C)) (computation state)
        (fun (function_parameter : B * C) =>
          let '(value, state) := function_parameter in
          body value state).
    
    Definition op_gtgteq `{_fargs : FArgs} {A B C D : Set}
      : (A -> Inner.(MONAD.t) (B * C)) -> (B -> C -> Inner.(MONAD.t) D) -> A ->
      Inner.(MONAD.t) D := bind.
    
    Definition Make_include_fargs `{_fargs : FArgs} :=
      Make.Build_FArgs
        (let t (a : Set) : Set := t a in
        let _return {A B : Set} : A -> B -> Inner.(MONAD.t) (A * B) :=
          _return in
        let bind {A B C D : Set}
          : (A -> Inner.(MONAD.t) (B * C)) -> (B -> C -> Inner.(MONAD.t) D) ->
          A -> Inner.(MONAD.t) D :=
          bind in
        ({|
          MONAD._return _ := _return;
          MONAD.bind _ _ := bind
        |} : MONAD (t := t))).
    
    Definition Make_include `{_fargs : FArgs} :
      Make.Make_result (_fargs := Make_include_fargs) :=
      Make
        (let t (a : Set) : Set := t a in
        let _return {A B : Set} : A -> B -> Inner.(MONAD.t) (A * B) :=
          _return in
        let bind {A B C D : Set}
          : (A -> Inner.(MONAD.t) (B * C)) -> (B -> C -> Inner.(MONAD.t) D) ->
          A -> Inner.(MONAD.t) D :=
          bind in
        ({|
          MONAD._return _ := _return;
          MONAD.bind _ _ := bind
        |} : MONAD (t := t))).
    
    (** Inclusion of the module [Make_include] *)
    Module Seq.
      Definition sequence `{_fargs : FArgs} {A : Set} :=
        Make_include.(Make.Make_result.Seq_sequence) (A := A).
    End Seq.
  End M.
  
  Module State_result.
    Record signature `{_fargs : FArgs} : Set := {
      state := T.(State_T_signature.t);
      Inner : MONAD (t := fun (a : Set) => Inner_parameter.(MONAD.t) a);
      M_t := fun (a : Set) => state -> Inner_parameter.(MONAD.t) (a * state);
      M_return :
        forall {A B : Set} , A -> B -> Inner_parameter.(MONAD.t) (A * B);
      M_bind :
        forall {A B C D : Set} ,
          (A -> Inner_parameter.(MONAD.t) (B * C)) ->
          (B -> C -> Inner_parameter.(MONAD.t) D) -> A ->
          Inner_parameter.(MONAD.t) D;
      op_M_gtgteq :
        forall {A B C D : Set} ,
          (A -> Inner_parameter.(MONAD.t) (B * C)) ->
          (B -> C -> Inner_parameter.(MONAD.t) D) -> A ->
          Inner_parameter.(MONAD.t) D;
      M_Seq_sequence :
        forall {A : Set} ,
          RocqOfOCaml.OCamlSeq.t (M_t A) ->
          RocqOfOCaml.Partial.Resumption.t
            (fun (a : Set) => state -> Inner_parameter.(MONAD.t) (a * state))
            (RocqOfOCaml.OCamlSeq.t A);
    }.
  End State_result.
  Definition State_result `{_fargs : FArgs} := @State_result.signature _ _ _.
  Arguments State_result {_ _ _}.
  
  (* State *)
  Definition functor `{_fargs : FArgs} :@State_result T_t Inner_t _fargs :=
    ({|
      State_result.Inner (T_t := T_t) (Inner_t := Inner_t) (_fargs := _fargs) :=
        (Inner (_fargs := _fargs));
      State_result.M_return (T_t := T_t) (Inner_t := Inner_t) (_fargs := _fargs)
        _ _ := (M._return (_fargs := _fargs));
      State_result.M_bind (T_t := T_t) (Inner_t := Inner_t) (_fargs := _fargs) _
        _ _ _ := (M.bind (_fargs := _fargs));
      State_result.op_M_gtgteq (T_t := T_t) (Inner_t := Inner_t) (_fargs :=
        _fargs) _ _ _ _ := (M.op_gtgteq (_fargs := _fargs));
      State_result.M_Seq_sequence (T_t := T_t) (Inner_t := Inner_t) (_fargs :=
        _fargs) _ := (M.Seq.sequence (_fargs := _fargs))
    |} : @State_result T_t Inner_t _fargs).
End State.
Definition State {T_t : Set} {Inner_t : Set -> Set}
  (T : State_T_signature (t := T_t)) (Inner_parameter : MONAD (t := Inner_t)) :=
  @State.functor T_t Inner_t (State.Build_FArgs T Inner_parameter).

Definition StateInt_fargs :=
  State.Build_FArgs
    (let t : Set := int in
    ((ltac:(constructor) : State_T_signature (t := t)) :
      State_T_signature (t := t))) Identity.

Definition StateInt : State.State_result (_fargs := StateInt_fargs) :=
  State
    (let t : Set := int in
    ((ltac:(constructor) : State_T_signature (t := t)) :
      State_T_signature (t := t))) Identity.

Module PARAM.
  Record signature : Set := {
    enabled : bool;
  }.
End PARAM.
Definition PARAM := PARAM.signature.

Module Instantiate.
  Class FArgs := {
    Param : PARAM;
  }.
  
  Module Host.
    Module M.
      Definition t `{_fargs : FArgs} (a : Set) :=
        StateInt.(State.State_result.M_t) a.
      
      Definition _return `{_fargs : FArgs} {A B : Set} :=
        StateInt.(State.State_result.M_return) (A := A) (B := B).
      
      Definition bind `{_fargs : FArgs} {A B C D : Set} :=
        StateInt.(State.State_result.M_bind) (A := A) (B := B) (C := C) (D := D).
      
      Definition op_gtgteq `{_fargs : FArgs} {A B C D : Set} :=
        StateInt.(State.State_result.op_M_gtgteq) (A := A) (B := B) (C := C) (D
          := D).
      
      Module Seq.
        Definition sequence `{_fargs : FArgs} {A : Set} :=
          StateInt.(State.State_result.M_Seq_sequence) (A := A).
      End Seq.
    End M.
  End Host.
  
  Definition enabled `{_fargs : FArgs} : bool := Param.(PARAM.enabled).
  
  Module Instantiate_result.
    Record signature `{_fargs : FArgs} : Set := {
      Host_M_t := fun (a : Set) => int -> Identity.(MONAD.t) (a * int);
      Host_M_return : forall {A B : Set} , A -> B -> A * B;
      Host_M_bind :
        forall {A B C D : Set} , (A -> B * C) -> (B -> C -> D) -> A -> D;
      op_Host_M_gtgteq :
        forall {A B C D : Set} , (A -> B * C) -> (B -> C -> D) -> A -> D;
      Host_M_Seq_sequence :
        forall {A : Set} ,
          RocqOfOCaml.OCamlSeq.t (StateInt.(State.State_result.M_t) A) ->
          RocqOfOCaml.Partial.Resumption.t
            (fun (a : Set) => int -> Identity.(MONAD.t) (a * int))
            (RocqOfOCaml.OCamlSeq.t A);
      enabled : bool;
    }.
  End Instantiate_result.
  Definition Instantiate_result `{_fargs : FArgs} :=
    @Instantiate_result.signature _.
  Arguments Instantiate_result {_}.
  
  (* Instantiate *)
  Definition functor `{_fargs : FArgs} :@Instantiate_result _fargs :=
    ({|
      Instantiate_result.Host_M_return (_fargs := _fargs) _ _ :=
        (Host.M._return (_fargs := _fargs));
      Instantiate_result.Host_M_bind (_fargs := _fargs) _ _ _ _ :=
        (Host.M.bind (_fargs := _fargs));
      Instantiate_result.op_Host_M_gtgteq (_fargs := _fargs) _ _ _ _ :=
        (Host.M.op_gtgteq (_fargs := _fargs));
      Instantiate_result.Host_M_Seq_sequence (_fargs := _fargs) _ :=
        (Host.M.Seq.sequence (_fargs := _fargs));
      Instantiate_result.enabled (_fargs := _fargs) :=
        (enabled (_fargs := _fargs))
    |} : @Instantiate_result _fargs).
End Instantiate.
Definition Instantiate (Param : PARAM) :=
  @Instantiate.functor (Instantiate.Build_FArgs Param).

Module Package.
  Class FArgs := {
    Param : PARAM;
  }.
  
  Definition Instantiation_fargs `{_fargs : FArgs} :=
    Instantiate.Build_FArgs Param.
  
  Definition Instantiation `{_fargs : FArgs} :
    Instantiate.Instantiate_result (_fargs := Instantiation_fargs) :=
    Instantiate Param.
  
  Module Host.
    Module M.
      Definition t `{_fargs : FArgs} (a : Set) :=
        Instantiation.(Instantiate.Instantiate_result.Host_M_t) a.
      
      Definition _return `{_fargs : FArgs} {A B : Set} :=
        Instantiation.(Instantiate.Instantiate_result.Host_M_return) (A := A) (B
          := B).
      
      Definition bind `{_fargs : FArgs} {A B C D : Set} :=
        Instantiation.(Instantiate.Instantiate_result.Host_M_bind) (A := A) (B
          := B) (C := C) (D := D).
      
      Definition op_gtgteq `{_fargs : FArgs} {A B C D : Set} :=
        Instantiation.(Instantiate.Instantiate_result.op_Host_M_gtgteq) (A := A)
          (B := B) (C := C) (D := D).
      
      Module Seq.
        Definition sequence `{_fargs : FArgs} {A : Set} :=
          Instantiation.(Instantiate.Instantiate_result.Host_M_Seq_sequence) (A
            := A).
      End Seq.
    End M.
  End Host.
  
  Definition enabled `{_fargs : FArgs} : bool :=
    Instantiation.(Instantiate.Instantiate_result.enabled).
  
  Module Package_result.
    Record signature `{_fargs : FArgs} : Set := {
      Instantiation :
        Instantiate.Instantiate_result (_fargs := Instantiation_fargs);
      Host_M_t := fun (a : Set) => int -> Identity.(MONAD.t) (a * int);
      Host_M_return : forall {A B : Set} , A -> B -> A * B;
      Host_M_bind :
        forall {A B C D : Set} , (A -> B * C) -> (B -> C -> D) -> A -> D;
      op_Host_M_gtgteq :
        forall {A B C D : Set} , (A -> B * C) -> (B -> C -> D) -> A -> D;
      Host_M_Seq_sequence :
        forall {A : Set} ,
          RocqOfOCaml.OCamlSeq.t (StateInt.(State.State_result.M_t) A) ->
          RocqOfOCaml.Partial.Resumption.t
            (fun (a : Set) => int -> Identity.(MONAD.t) (a * int))
            (RocqOfOCaml.OCamlSeq.t A);
      enabled : bool;
    }.
  End Package_result.
  Definition Package_result `{_fargs : FArgs} := @Package_result.signature _.
  Arguments Package_result {_}.
  
  (* Package *)
  Definition functor `{_fargs : FArgs} :@Package_result _fargs :=
    ({|
      Package_result.Instantiation (_fargs := _fargs) :=
        (Instantiation (_fargs := _fargs));
      Package_result.Host_M_return (_fargs := _fargs) _ _ :=
        (Host.M._return (_fargs := _fargs));
      Package_result.Host_M_bind (_fargs := _fargs) _ _ _ _ :=
        (Host.M.bind (_fargs := _fargs));
      Package_result.op_Host_M_gtgteq (_fargs := _fargs) _ _ _ _ :=
        (Host.M.op_gtgteq (_fargs := _fargs));
      Package_result.Host_M_Seq_sequence (_fargs := _fargs) _ :=
        (Host.M.Seq.sequence (_fargs := _fargs));
      Package_result.enabled (_fargs := _fargs) := (enabled (_fargs := _fargs))
    |} : @Package_result _fargs).
End Package.
Definition Package (Param : PARAM) :=
  @Package.functor (Package.Build_FArgs Param).
