(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module lens.
  Record record {source focus : Set} : Set := Build {
    get : source -> focus;
    set : focus -> source -> source;
  }.
  Arguments record : clear implicits.
  Definition with_get {t_source t_focus} get (r : record t_source t_focus) :=
    Build t_source t_focus get r.(set).
  Definition with_set {t_source t_focus} set (r : record t_source t_focus) :=
    Build t_source t_focus r.(get) set.
End lens.
Definition lens := lens.record.

Definition option_get {A : Set}
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A} : option A -> A :=
  RocqOfOCaml.OCamlOption.get.

Definition with_default {a : Set} (default : a) : lens (option a) a :=
  {|
    lens.get :=
      fun (function_parameter : option a) =>
        match function_parameter with
        | None => default
        | Some value => value
        end;
    lens.set :=
      fun (value : a) =>
        fun (function_parameter : option a) =>
          let '_ := function_parameter in
          Some value; |}.
