(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

CoFixpoint loop {A : Set} (function_parameter : unit)
  : RocqOfOCaml.Partial.Delay.t A :=
  RocqOfOCaml.Partial.Delay.Tau
    (fun _ =>
      let '_ := function_parameter in
      RocqOfOCaml.Partial.Delay.Tau (fun _ => loop tt)).
