(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition consume (bound : int) : RocqOfOCaml.Partial.Delay.t int :=
  let cofix loop (value : int) : RocqOfOCaml.Partial.Delay.t int :=
    RocqOfOCaml.Partial.Delay.Tau
      (fun _ =>
        if RocqOfOCaml.Basics.Stdlib.lt value bound then
          RocqOfOCaml.Partial.Delay.Tau (fun _ => loop (Z.add value 1))
        else
          RocqOfOCaml.Partial.Delay.Done value) in
  loop 0.
