(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module PARAMS.
  Record signature : Type := {
    enabled : bool;
  }.
End PARAMS.
Definition PARAMS := PARAMS.signature.

Module HOST.
  Record signature : Type := {
    initial : unit;
  }.
End HOST.
Definition HOST := HOST.signature.

Module VM.
  Record signature : Type := {
    execute : unit -> int;
  }.
End VM.
Definition VM := VM.signature.

Module Make_vm.
  Class FArgs := {
    Params : PARAMS;
    Host : HOST;
  }.

  Definition address `{_fargs : FArgs} : Set := int.

  Definition invalid_address `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable address}
    (function_parameter : unit) : address :=
    let '_ := function_parameter in
    let '_ := false in
    (@RocqOfOCaml.Basics.unreachable address _).

  Definition execute `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable address}
    (function_parameter : unit) : address :=
    let '_ := function_parameter in
    invalid_address tt.

  Module Make_vm_result.
    Record signature `{_fargs : FArgs} : Type := {
      address := int;
      invalid_address :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int},
          unit -> int;
      execute :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int},
          unit -> int;
    }.
  End Make_vm_result.
  Definition Make_vm_result `{_fargs : FArgs} := @Make_vm_result.signature _.
  Arguments Make_vm_result {_}.

  (* Make_vm *)
  Definition functor `{_fargs : FArgs} :@Make_vm_result _fargs :=
    ((@Make_vm_result.Build_signature _fargs (fun _ => invalid_address)
      (fun _ => execute)) : @Make_vm_result _fargs).
End Make_vm.
Definition Make_vm (Params : PARAMS) (Host : HOST) :=
  @Make_vm.functor (Make_vm.Build_FArgs Params Host).

Module Instantiate.
  Class FArgs := {
    Vm_parameter : forall (Host : HOST), VM;
  }.

  Module Host.
    Definition initial `{_fargs : FArgs} : unit := tt.

    (* Host *)
    Definition module `{_fargs : FArgs} :HOST :=
      {|
        HOST.initial := initial
      |}.
  End Host.
  Definition Host `{_fargs : FArgs} := Host.module.

  Definition Vm `{_fargs : FArgs} := Vm_parameter Host.

  Module Instantiate_result.
    Record signature `{_fargs : FArgs} : Type := {
      Host : HOST;
      Vm : VM;
    }.
  End Instantiate_result.
  Definition Instantiate_result `{_fargs : FArgs} :=
    @Instantiate_result.signature _.
  Arguments Instantiate_result {_}.

  (* Instantiate *)
  Definition functor `{_fargs : FArgs} :@Instantiate_result _fargs :=
    ((@Instantiate_result.Build_signature _fargs Host Vm) :
      @Instantiate_result _fargs).
End Instantiate.
Definition Instantiate (Vm_parameter : forall (Host : HOST), VM) :=
  @Instantiate.functor (Instantiate.Build_FArgs Vm_parameter).

Module Apply.
  Class FArgs := {
    Params : PARAMS;
  }.

  Definition Result_fargs `{_fargs : FArgs}
    `{_rocq_module_assumption_0 :
      RocqOfOCaml.Basics.Unreachable
        (forall (Host : HOST),
        (Make_vm.address (_fargs := Make_vm.Build_FArgs Params Host)))} :=
    Instantiate.Build_FArgs
      (fun (Host : HOST) =>
        let _rocq_local__rocq_module_assumption_0 :=
          specialize_unreachable _rocq_module_assumption_0 Host in
        let module_coercion := Make_vm Params Host in
        {|
          VM.execute := module_coercion.(Make_vm.Make_vm_result.execute)
        |}).

  Definition Result `{_fargs : FArgs}
    `{_rocq_module_assumption_0 :
      RocqOfOCaml.Basics.Unreachable
        (forall (Host : HOST),
        (Make_vm.address (_fargs := Make_vm.Build_FArgs Params Host)))} :
    Instantiate.Instantiate_result (_fargs := Result_fargs) :=
    Instantiate
      (fun (Host : HOST) =>
        let _rocq_local__rocq_module_assumption_0 :=
          specialize_unreachable _rocq_module_assumption_0 Host in
        let module_coercion := Make_vm Params Host in
        {|
          VM.execute := module_coercion.(Make_vm.Make_vm_result.execute)
        |}).

  Module Apply_result.
    Record signature `{_fargs : FArgs} : Type := {
      Result :
        forall
          `{_rocq_assumption_0 :
            RocqOfOCaml.Basics.Unreachable
              (forall (Host : HOST),
              (Make_vm.address (_fargs := Make_vm.Build_FArgs Params Host)))},
          Instantiate.Instantiate_result (_fargs := Result_fargs);
    }.
  End Apply_result.
  Definition Apply_result `{_fargs : FArgs} := @Apply_result.signature _.
  Arguments Apply_result {_}.

  (* Apply *)
  Definition functor `{_fargs : FArgs} :@Apply_result _fargs :=
    ((@Apply_result.Build_signature _fargs (fun _ => Result)) :
      @Apply_result _fargs).
End Apply.
Definition Apply (Params : PARAMS) := @Apply.functor (Apply.Build_FArgs Params).
