(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Mapped.
  Inductive t : Set := A | B (n : Z).
End Mapped.
Definition t : Set := Mapped.t.

Definition a_value : t := Mapped.A.

Definition b_value : t := Mapped.B 1.

Definition payload (function_parameter : Mapped.t) : int :=
  match function_parameter with
  | Mapped.A => 0
  | Mapped.B n_value => n_value
  end.

#[local] Instance _rocq_assumption_only_a_0 :
  RocqOfOCaml.Basics.Unreachable int.
Admitted.

Definition only_a (x_value : Mapped.t) : int :=
  match x_value with
  | Mapped.A => 1
  | _ => (@RocqOfOCaml.Basics.unreachable int _)
  end.
