(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition u_value : unit := tt.

Definition l1 {A : Set} : list A := nil.

Definition l2 : list int := Datatypes.cons 1 nil.

Definition l3 : list int :=
  Datatypes.cons 1
    (Datatypes.cons 5
      (Datatypes.cons 7 (Datatypes.cons 32 (Datatypes.cons 15 nil)))).

Definition o1 {A : Set} : option A := None.

Definition o2 : option int := Some 12.

Definition c_value : ascii := "g" % char.

Definition s1 : string := "bla".

Definition s2 : string := """".
