(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Sig1.
  Record signature {t : Set} : Type := {
    t := t;
    f_value : t -> t -> t * t;
  }.
End Sig1.
Definition Sig1 := @Sig1.signature.
Arguments Sig1 {_}.

Module Sig2.
  Record signature {t : Set} : Type := {
    t := t;
    f_value : t -> list t;
  }.
End Sig2.
Definition Sig2 := @Sig2.signature.
Arguments Sig2 {_}.

Module M1.
  Definition t : Set := int.

  Definition f_value {A : Set} (n_value : t) (m_value : A) : t * A :=
    (n_value, m_value).

  (* M1 *)
  Definition module :Sig1 (t := t) :=
    {|
      Sig1.f_value := f_value
    |}.
End M1.
Definition M1 := M1.module.

Module M2.
  Definition t : Set := int.

  Definition f_value {A : Set} (n_value : t) : list A := nil.

  (* M2 *)
  Definition module :Sig2 (t := t) :=
    {|
      Sig2.f_value := f_value
    |}.
End M2.
Definition M2 := M2.module.
