(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Make_P_signature.
  Record signature : Type := {
    enabled : bool;
  }.
End Make_P_signature.
Definition Make_P_signature := Make_P_signature.signature.

Module Make.
  Class FArgs := {
    P : Make_P_signature;
  }.
  
  Module Memory.
    Definition empty `{_fargs : FArgs} {A : Set}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
      `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable A} (x_value : A)
      : A :=
      let '_ :=
        if P.(Make_P_signature.enabled) then
          tt
        else
          if false then tt else (@RocqOfOCaml.Basics.unreachable unit _) in
      RocqOfOCaml.OCamlOption.get (Some x_value).
    
    Module Memory_signature.
      Record signature `{_fargs : FArgs} : Type := {
        empty :
          forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
            `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int},
            int -> int;
      }.
    End Memory_signature.
    Definition Memory_signature `{_fargs : FArgs} := @Memory_signature.signature
      _.
    Arguments Memory_signature {_}.
    
    (* Memory *)
    Definition module `{_fargs : FArgs} :Memory_signature :=
      {|
        Memory_signature.empty _ _ := empty
      |}.
  End Memory.
  Definition Memory `{_fargs : FArgs} := Memory.module.
  
  Definition initial `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int} (x_value : int)
    : int :=
    (Memory.(Memory.Memory_signature.empty)
      (_rocq_assumption_0 := _rocq_assumption_0)
      (_rocq_assumption_1 := _rocq_assumption_1)) x_value.
  
  Module Make_result.
    Record signature `{_fargs : FArgs} : Type := {
      Memory : Make.Memory.Memory_signature;
      initial :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
          `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}, int -> int;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result _fargs :=
    ((@Make_result.Build_signature _fargs Memory (fun _ _ => initial)) :
      @Make_result _fargs).
End Make.
Definition Make (P : Make_P_signature) := @Make.functor (Make.Build_FArgs P).

Definition Built_fargs :=
  Make.Build_FArgs
    (let enabled := true in
    ({|
      Make_P_signature.enabled := enabled
    |} : Make_P_signature)).

Definition Built : Make.Make_result (_fargs := Built_fargs) := (Make.functor
  (_fargs := (Built_fargs ))).

Definition initial
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
  `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int} : int -> int :=
  (Built.(Make.Make_result.initial) (_rocq_assumption_0 := _rocq_assumption_0)
    (_rocq_assumption_1 := _rocq_assumption_1)).
