(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module FIELD.
  Record signature {t : Set} : Type := {
    t := t;
    zero : t;
    sub : t -> t -> t;
  }.
End FIELD.
Definition FIELD := @FIELD.signature.
Arguments FIELD {_}.

Module Use.
  Class FArgs {F_t : Set} := {
    F : FIELD (t := F_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition value `{_fargs : FArgs} : F.(FIELD.t) :=
    F.(FIELD.sub) F.(FIELD.zero) F.(FIELD.zero).
  
  Module Use_result.
    Record signature `{_fargs : FArgs} : Type := {
      value : F.(FIELD.t);
    }.
  End Use_result.
  Definition Use_result `{_fargs : FArgs} := @Use_result.signature _ _.
  Arguments Use_result {_ _}.
  
  (* Use *)
  Definition functor `{_fargs : FArgs} :@Use_result F_t _fargs :=
    ((@Use_result.Build_signature F_t _fargs value) : @Use_result F_t _fargs).
End Use.
Definition Use {F_t : Set} (F : FIELD (t := F_t)) :=
  @Use.functor F_t (Use.Build_FArgs F).

Module MakeField_Seed_signature.
  Record signature {t : Set} : Type := {
    t := t;
    seed : t;
    sub : t -> t -> t;
  }.
End MakeField_Seed_signature.
Definition MakeField_Seed_signature := @MakeField_Seed_signature.signature.
Arguments MakeField_Seed_signature {_}.

Module MakeField.
  Class FArgs {Seed_t : Set} := {
    Seed : MakeField_Seed_signature (t := Seed_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition t `{_fargs : FArgs} : Set := Seed.(MakeField_Seed_signature.t).
  
  Definition zero `{_fargs : FArgs}
    `{_rocq_assumption_0 :
      RocqOfOCaml.Basics.Unreachable Seed.(MakeField_Seed_signature.t)} : Seed.(MakeField_Seed_signature.t) :=
    if true then
      Seed.(MakeField_Seed_signature.seed)
    else
      let '_ := "unreachable" in
      (@RocqOfOCaml.Basics.unreachable Seed.(MakeField_Seed_signature.t) _).
  
  Definition sub `{_fargs : FArgs}
    `{_rocq_assumption_0 :
      RocqOfOCaml.Basics.Unreachable Seed.(MakeField_Seed_signature.t)}
    (x_value : Seed.(MakeField_Seed_signature.t))
    (y_value : Seed.(MakeField_Seed_signature.t))
    : Seed.(MakeField_Seed_signature.t) :=
    if true then
      Seed.(MakeField_Seed_signature.sub) x_value y_value
    else
      let '_ := "unreachable" in
      (@RocqOfOCaml.Basics.unreachable Seed.(MakeField_Seed_signature.t) _).
  
  Definition extra `{_fargs : FArgs} : unit := tt.
  
  Module MakeField_result.
    Record signature `{_fargs : FArgs} : Type := {
      t := Seed.(MakeField_Seed_signature.t);
      zero :
        forall
          `{_rocq_assumption_0 :
            RocqOfOCaml.Basics.Unreachable Seed.(MakeField_Seed_signature.t)},
          Seed.(MakeField_Seed_signature.t);
      sub :
        forall
          `{_rocq_assumption_0 :
            RocqOfOCaml.Basics.Unreachable Seed.(MakeField_Seed_signature.t)},
          Seed.(MakeField_Seed_signature.t) ->
          Seed.(MakeField_Seed_signature.t) -> Seed.(MakeField_Seed_signature.t);
      extra : unit;
    }.
  End MakeField_result.
  Definition MakeField_result `{_fargs : FArgs} := @MakeField_result.signature _
    _.
  Arguments MakeField_result {_ _}.
  
  (* MakeField *)
  Definition functor `{_fargs : FArgs} :@MakeField_result Seed_t _fargs :=
    ((@MakeField_result.Build_signature Seed_t _fargs (fun _ => zero)
      (fun _ => sub) extra) : @MakeField_result Seed_t _fargs).
End MakeField.
Definition MakeField {Seed_t : Set}
  (Seed : MakeField_Seed_signature (t := Seed_t)) :=
  @MakeField.functor Seed_t (MakeField.Build_FArgs Seed).

Definition Base_fargs
  `{_rocq_module_assumption_0 : RocqOfOCaml.Basics.Unreachable int} :=
  MakeField.Build_FArgs
    (let t : Set := int in
    let seed :=
      if true then
        0
      else
        let '_ := "unreachable" in
        (@RocqOfOCaml.Basics.unreachable int _) in
    let sub (x_value : int) (y_value : int) : int :=
      Z.sub x_value y_value in
    ({|
      MakeField_Seed_signature.seed := seed;
      MakeField_Seed_signature.sub := sub
    |} : MakeField_Seed_signature (t := t))).

Definition Base
  `{_rocq_module_assumption_0 : RocqOfOCaml.Basics.Unreachable int} :
  MakeField.MakeField_result
    (_fargs :=
      (Base_fargs (_rocq_module_assumption_0 := _rocq_module_assumption_0))) :=
  (MakeField.functor
  (_fargs :=
    (Base_fargs (_rocq_module_assumption_0 := _rocq_module_assumption_0)))).

Definition keep_extra
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int} : unit :=
  (Base (_rocq_module_assumption_0 := _rocq_assumption_0)).(MakeField.MakeField_result.extra).

Definition Result_fargs
  `{_rocq_module_assumption_0 : RocqOfOCaml.Basics.Unreachable int}
  `{_rocq_module_assumption_1 :
    RocqOfOCaml.Basics.Unreachable
      (Base (_rocq_module_assumption_0 := _rocq_module_assumption_0)).(MakeField.MakeField_result.t)}
  :=
  Use.Build_FArgs
    ({|
      FIELD.zero :=
        ((Base (_rocq_module_assumption_0 := _rocq_module_assumption_0)).(MakeField.MakeField_result.zero)
          (_rocq_assumption_0 := _rocq_module_assumption_1));
      FIELD.sub :=
        ((Base (_rocq_module_assumption_0 := _rocq_module_assumption_0)).(MakeField.MakeField_result.sub)
          (_rocq_assumption_0 := _rocq_module_assumption_1))
    |} :
      FIELD
        (t :=
          (Base (_rocq_module_assumption_0 := _rocq_module_assumption_0)).(MakeField.MakeField_result.t))).

Definition Result
  `{_rocq_module_assumption_0 : RocqOfOCaml.Basics.Unreachable int}
  `{_rocq_module_assumption_1 :
    RocqOfOCaml.Basics.Unreachable
      (Base (_rocq_module_assumption_0 := _rocq_module_assumption_0)).(MakeField.MakeField_result.t)}
  :
  Use.Use_result
    (_fargs :=
      (Result_fargs (_rocq_module_assumption_0 := _rocq_module_assumption_0) (_rocq_module_assumption_1 := _rocq_module_assumption_1)))
  := (Use.functor
  (_fargs :=
    (Result_fargs (_rocq_module_assumption_0 := _rocq_module_assumption_0) (_rocq_module_assumption_1 := _rocq_module_assumption_1)))).
