(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module PARAM.
  Record signature : Type := {
    fallback : string;
  }.
End PARAM.
Definition PARAM := PARAM.signature.

Module Make.
  Class FArgs := {
    Param : PARAM;
  }.
  
  Module Host.
    Definition t `{_fargs : FArgs} : Set := string.
  End Host.
  
  Definition initial `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Host.t}
    (function_parameter : unit) : Host.t :=
    let '_ := function_parameter in
    if true then
      Param.(PARAM.fallback)
    else
      let '_ := false in
      (@RocqOfOCaml.Basics.unreachable Host.t _).
  
  Module Make_result.
    Record signature `{_fargs : FArgs} : Type := {
      Host_t := string;
      initial :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string},
          unit -> Host_t;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result _fargs :=
    ((@Make_result.Build_signature _fargs (fun _ => initial)) :
      @Make_result _fargs).
End Make.
Definition Make (Param : PARAM) := @Make.functor (Make.Build_FArgs Param).
