(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module A.
  Record signature : Set := {
    even : int -> bool;
  }.
End A.
Definition A := A.signature.

Module B.
  Record signature : Set := {
    odd : int -> bool;
  }.
End B.
Definition B := B.signature.

Module Instantiate.
  Class FArgs := {
    MakeA : forall (Other : B), A;
    MakeB : forall (Other : A), B;
  }.
  
  Definition _recursive_modules_First_Second `{_fargs : FArgs} : A * B :=
    recursive_module_fix
      (fun (_recursive_modules : A * B) =>
        let First := fst _recursive_modules in
        let Second := snd _recursive_modules in
        ((MakeA Second), (MakeB First))).
  
  Definition First `{_fargs : FArgs} : A := fst _recursive_modules_First_Second.
  
  Definition Second `{_fargs : FArgs} : B :=
    snd _recursive_modules_First_Second.
  
  Definition two_is_even `{_fargs : FArgs} : bool := First.(A.even) 2.
  
  Module Instantiate_result.
    Record signature `{_fargs : FArgs} : Set := {
      First : A;
      Second : B;
      two_is_even : bool;
    }.
  End Instantiate_result.
  Definition Instantiate_result `{_fargs : FArgs} :=
    @Instantiate_result.signature _.
  Arguments Instantiate_result {_}.
  
  (* Instantiate *)
  Definition functor `{_fargs : FArgs} :@Instantiate_result _fargs :=
    ({|
      Instantiate_result.First (_fargs := _fargs) := (First (_fargs := _fargs));
      Instantiate_result.Second (_fargs := _fargs) :=
        (Second (_fargs := _fargs));
      Instantiate_result.two_is_even (_fargs := _fargs) :=
        (two_is_even (_fargs := _fargs))
    |} : @Instantiate_result _fargs).
End Instantiate.
Definition Instantiate
  (MakeA : forall (Other : B), A) (MakeB : forall (Other : A), B) :=
  @Instantiate.functor (Instantiate.Build_FArgs MakeA MakeB).

Module MakeA.
  Class FArgs := {
    Other : B;
  }.
  
  Fixpoint even `{_fargs : FArgs} (n_value : int) : bool :=
    orb (equiv_decb n_value 0) (Other.(B.odd) (Z.sub n_value 1)).
  
  (* MakeA *)
  Definition functor `{_fargs : FArgs} :A :=
    {|
      A.even := (even (_fargs := _fargs))
    |}.
End MakeA.
Definition MakeA (Other : B) := @MakeA.functor (MakeA.Build_FArgs Other).

Module MakeB.
  Class FArgs := {
    Other : A;
  }.
  
  Fixpoint odd `{_fargs : FArgs} (n_value : int) : bool :=
    andb (nequiv_decb n_value 0) (Other.(A.even) (Z.sub n_value 1)).
  
  (* MakeB *)
  Definition functor `{_fargs : FArgs} :B :=
    {|
      B.odd := (odd (_fargs := _fargs))
    |}.
End MakeB.
Definition MakeB (Other : A) := @MakeB.functor (MakeB.Build_FArgs Other).

Definition Instance_fargs := Instantiate.Build_FArgs MakeA MakeB.

Definition Instance : Instantiate.Instantiate_result (_fargs := Instance_fargs)
  := Instantiate MakeA MakeB.

Definition four_is_even : bool :=
  Instance.(Instantiate.Instantiate_result.First).(A.even) 4.

Module TYPE.
  Record signature {t : Set} : Set := {
    t := t;
  }.
End TYPE.
Definition TYPE := @TYPE.signature.
Arguments TYPE {_}.

Module Box.
  Class FArgs {T_t : Set} := {
    T : TYPE (t := T_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module S.
    Record signature `{_fargs : FArgs} : Set := {
      run : T.(TYPE.t) -> T.(TYPE.t);
    }.
  End S.
  Definition S `{_fargs : FArgs} := @S.signature _ _.
  Arguments S {_ _}.
  
  Module Box_result.
    Inductive signature `{_fargs : FArgs} : Set :=
    | Build_signature : signature.
  End Box_result.
  Definition Box_result `{_fargs : FArgs} := @Box_result.signature _ _.
  Arguments Box_result {_ _}.
  
  (* Box *)
  Definition functor `{_fargs : FArgs} :@Box_result T_t _fargs :=
    ((ltac:(constructor) : Box_result) : @Box_result T_t _fargs).
End Box.
Definition Box {T_t : Set} (T : TYPE (t := T_t)) :=
  @Box.functor T_t (Box.Build_FArgs T).

Module RecursiveResult.
  Class FArgs {T_t : Set} := {
    T : TYPE (t := T_t);
    MakeWorker :
      forall (X : TYPE (t := T.(TYPE.t))), Box.S (_fargs := Box.Build_FArgs T);
  }.
  Arguments Build_FArgs {_}.
  
  Definition _recursive_modules_Worker `{_fargs : FArgs} :
    Box.S (_fargs := Box.Build_FArgs T) :=
    recursive_module_fix
      (fun (_recursive_modules : Box.S (_fargs := Box.Build_FArgs T)) =>
        let Worker := _recursive_modules in
        MakeWorker T).
  
  Definition Worker `{_fargs : FArgs} : Box.S (_fargs := Box.Build_FArgs T) :=
    _recursive_modules_Worker.
  
  Module RecursiveResult_signature.
    Record signature `{_fargs : FArgs} : Set := {
      Worker_run : T.(TYPE.t) -> T.(TYPE.t);
    }.
  End RecursiveResult_signature.
  Definition RecursiveResult_signature `{_fargs : FArgs} :=
    @RecursiveResult_signature.signature _ _.
  Arguments RecursiveResult_signature {_ _}.
  
  (* RecursiveResult *)
  Definition functor `{_fargs : FArgs} :RecursiveResult_signature :=
    {|
      RecursiveResult_signature.Worker_run :=
        (Worker (_fargs := _fargs)).(Box.S.run)
    |}.
End RecursiveResult.
Definition RecursiveResult {T_t : Set}
  (T : TYPE (t := T_t))
  (MakeWorker :
    forall (X : TYPE (t := T.(TYPE.t))), Box.S (_fargs := Box.Build_FArgs T)) :=
  @RecursiveResult.functor T_t (RecursiveResult.Build_FArgs T MakeWorker).
