(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Source.
  Definition map (value : int) : int := Z.add value 1.
End Source.

Module Uses_include.
  Definition apply (value : int) : int := Source.map value.
  
  Include Source.
End Uses_include.

Definition result_value : int := Uses_include.apply 2.
