(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

(** [Stdlib.Map] is mapped to the executable Gallina compatibility layer. *)
Module Int_order.
  Definition t : Set := int.
  
  Definition compare (_left : int) (_right : int) : int := Z.sub _left _right.
  
  (* Int_order *)
  Definition module :RocqOfOCaml.OCamlMap.OrderedType (t := int) :=
    {|
      RocqOfOCaml.OCamlMap.OrderedType.compare := compare
    |}.
End Int_order.
Definition Int_order := Int_order.module.

Definition Int_map := RocqOfOCaml.OCamlMap.Make Int_order.

Definition example : Int_map.(RocqOfOCaml.OCamlMap.S.t) string :=
  Int_map.(RocqOfOCaml.OCamlMap.S.add) 1 "one"
    (Int_map.(RocqOfOCaml.OCamlMap.S.add) 2 "two"
      Int_map.(RocqOfOCaml.OCamlMap.S.empty)).

Definition lookup_one : option string :=
  Int_map.(RocqOfOCaml.OCamlMap.S.find_opt) 1 example.
