(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition identity {value : Set} (value_value : value) : value := value_value.

Definition fold {acc item : Set}
  (combine : acc -> item -> acc) (acc_value : acc) (item_value : item) : acc :=
  combine acc_value item_value.
