(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module info.
  Record record : Set := Build {
    code : int;
  }.
  Definition with_code code (r : record) :=
    Build code.
End info.
Definition info := info.record.

Definition info_value (code : int) : info := {| info.code := code; |}.

Definition info_code (code : int) : int := (info_value code).(info.code).

Module Nested.
  Inductive status : Set :=
  | Ready : status
  | Failed : status.
  
  Definition status_value (ready : bool) : status :=
    if ready then
      Ready
    else
      Failed.
  
  Definition is_ready (ready : bool) : bool :=
    match status_value ready with
    | Ready => true
    | Failed => false
    end.
End Nested.

Definition nested_status (ready : bool) : Nested.status :=
  Nested.status_value ready.
