(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module ARGUMENT.
  Record signature : Type := {
    value : int;
  }.
End ARGUMENT.
Definition ARGUMENT := ARGUMENT.signature.

Module Operations.
  Class FArgs := {
    Argument : ARGUMENT;
  }.
  
  Definition get `{_fargs : FArgs} : int := Argument.(ARGUMENT.value).
  
  Definition increment `{_fargs : FArgs} (x_value : int) : int :=
    Z.add x_value 1.
  
  Module Operations_result.
    Record signature `{_fargs : FArgs} : Type := {
      get : int;
      increment : int -> int;
    }.
  End Operations_result.
  Definition Operations_result `{_fargs : FArgs} := @Operations_result.signature
    _.
  Arguments Operations_result {_}.
  
  (* Operations *)
  Definition functor `{_fargs : FArgs} :@Operations_result _fargs :=
    ((@Operations_result.Build_signature _fargs get increment) :
      @Operations_result _fargs).
End Operations.
Definition Operations (Argument : ARGUMENT) :=
  @Operations.functor (Operations.Build_FArgs Argument).

Definition opened_module_157_fargs :=
  Operations.Build_FArgs
    (let value := 41 in
    ({|
      ARGUMENT.value := value
    |} : ARGUMENT)).

Definition opened_module_157 :
  Operations.Operations_result (_fargs := opened_module_157_fargs) :=
  (Operations.functor (_fargs := (opened_module_157_fargs ))).

Definition read (function_parameter : unit) : int :=
  let '_ := function_parameter in
  opened_module_157.(Operations.Operations_result.increment)
    opened_module_157.(Operations.Operations_result.get).
