(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition recover {A : Set}
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
  (f_value : unit -> A) : sum A string :=
  try_with (fun _ => ((inl (f_value tt)) : sum A string))
    (fun _exception_value =>
      match _exception_value with
      | Build_extensible tag _ payload =>
        if String.eqb tag "Parse_error" then
          let message :=
            (let '_ := payload in
            (@RocqOfOCaml.Basics.unreachable string _)) in
          ((inr message) : sum A string)
        else
          ((inr "unknown") : sum A string)
      end).

Definition recover_any (value : int) : int :=
  try_with (fun _ => value)
    (fun _exception_value =>
      let '_ := _exception_value in
      0).

Definition recover_only {A : Set}
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
  `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable (sum A string)}
  (f_value : unit -> A) : sum A string :=
  try_with (fun _ => ((inl (f_value tt)) : sum A string))
    (fun _exception_value =>
      match _exception_value with
      | Build_extensible tag _ payload =>
        if String.eqb tag "Parse_error" then
          let message :=
            (let '_ := payload in
            (@RocqOfOCaml.Basics.unreachable string _)) in
          ((inr message) : sum A string)
        else
          (@RocqOfOCaml.Basics.unreachable (sum A string) _)
      end).
