(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Definition failed_int
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int}
  (function_parameter : unit) : int :=
  let '_ := function_parameter in
  let '_ := "impossible" in
  (@RocqOfOCaml.Basics.unreachable int _).

Definition invalid_string
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
  (function_parameter : unit) : string :=
  let '_ := function_parameter in
  let '_ := "invalid" in
  (@RocqOfOCaml.Basics.unreachable string _).

Definition raised_bool
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable bool}
  (function_parameter : unit) : bool :=
  let '_ := function_parameter in
  let '_ := Build_extensible "Failure_case" unit tt in
  (@RocqOfOCaml.Basics.unreachable bool _).

Definition missing_implementation
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unimplemented int}
  (function_parameter : unit) : int :=
  let '_ := function_parameter in
  let '_ := "todo 17" in
  (@RocqOfOCaml.Basics.unimplemented int _).

Definition failed_poly {a : Set}
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable a}
  (function_parameter : unit) : a :=
  let '_ := function_parameter in
  let '_ := "impossible polymorphic result" in
  (@RocqOfOCaml.Basics.unreachable a _).

Definition failed_poly_int
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int}
  (function_parameter : unit) : int :=
  let '_ := function_parameter in
  failed_poly tt.

Module Qualified.
  Definition failed_unit
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
    (function_parameter : unit) : unit :=
    let '_ := function_parameter in
    if false then tt else (@RocqOfOCaml.Basics.unreachable unit _).
End Qualified.

Definition failed_qualified
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
  (function_parameter : unit) : unit :=
  let '_ := function_parameter in
  Qualified.failed_unit tt.

Module Scoped_value_X_signature.
  Record signature : Set := {
    value : Variant.t;
  }.
End Scoped_value_X_signature.
Definition Scoped_value_X_signature := Scoped_value_X_signature.signature.

Module Scoped_value.
  Class FArgs := {
    X : Scoped_value_X_signature;
  }.
  
  Definition number `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int} : int :=
    let _variant_value := X.(Scoped_value_X_signature.value) in
    match _variant_value with
    | Variant.Build _variant_tag _ _variant_payload =>
      if String.eqb _variant_tag "Number" then
        let value := cast int _variant_payload in
        value
      else
        (@RocqOfOCaml.Basics.unreachable int _)
    end.
  
  Module Nested.
    Definition copied_number `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int} : int :=
      number.
  End Nested.
  
  Module Scoped_value_result.
    Record signature `{_fargs : FArgs} : Set := {
      number :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int}, int;
      Nested_copied_number :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int}, int;
    }.
  End Scoped_value_result.
  Definition Scoped_value_result `{_fargs : FArgs} :=
    @Scoped_value_result.signature _.
  Arguments Scoped_value_result {_}.
  
  (* Scoped_value *)
  Definition functor `{_fargs : FArgs} :@Scoped_value_result _fargs :=
    ({|
      Scoped_value_result.number (_fargs := _fargs) _ :=
        (number (_fargs := _fargs));
      Scoped_value_result.Nested_copied_number (_fargs := _fargs) _ :=
        (Nested.copied_number (_fargs := _fargs))
    |} : @Scoped_value_result _fargs).
End Scoped_value.
Definition Scoped_value (X : Scoped_value_X_signature) :=
  @Scoped_value.functor (Scoped_value.Build_FArgs X).

Module Outer_X_signature.
  Record signature {t : Set} : Set := {
    t := t;
    value : t;
  }.
End Outer_X_signature.
Definition Outer_X_signature := @Outer_X_signature.signature.
Arguments Outer_X_signature {_}.

Module Outer.
  Class FArgs {X_t : Set} := {
    X : Outer_X_signature (t := X_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module Inner_Y_signature.
    Record signature `{_fargs : FArgs} : Set := {
      valid : bool;
    }.
  End Inner_Y_signature.
  Definition Inner_Y_signature `{_fargs : FArgs} := @Inner_Y_signature.signature
    _ _.
  Arguments Inner_Y_signature {_ _}.
  
  Module Inner.
    Class FArgs `{_fargs : FArgs} := {
      Y : Inner_Y_signature;
    }.
    Arguments Build_FArgs {_ _}.
    
    Definition checked `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit}
      (function_parameter : unit) : X.(Outer_X_signature.t) :=
      let '_ := function_parameter in
      let '_ :=
        if Y.(Inner_Y_signature.valid) then tt else
          (@RocqOfOCaml.Basics.unreachable unit _) in
      X.(Outer_X_signature.value).
    
    Module Inner_result.
      Record signature `{_fargs : FArgs} : Set := {
        checked :
          forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable unit},
            unit -> X.(Outer_X_signature.t);
      }.
    End Inner_result.
    Definition Inner_result `{_fargs : FArgs} := @Inner_result.signature _ _ _.
    Arguments Inner_result {_ _ _}.
    
    (* Inner *)
    Definition functor `{_fargs : FArgs} :@Inner_result _ _ _fargs :=
      ({|
        Inner_result.checked (_fargs := _fargs) _ :=
          (checked (_fargs := _fargs))
      |} : @Inner_result _ _ _fargs).
  End Inner.
  Definition Inner `{_fargs : FArgs} (Y : Inner_Y_signature) :=
    @Inner.functor _ _ (Inner.Build_FArgs Y).
  
  Module Outer_result.
    Inductive signature `{_fargs : FArgs} : Set :=
    | Build_signature : signature.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _ _.
  Arguments Outer_result {_ _}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :@Outer_result X_t _fargs :=
    ((ltac:(constructor) : Outer_result) : @Outer_result X_t _fargs).
End Outer.
Definition Outer {X_t : Set} (X : Outer_X_signature (t := X_t)) :=
  @Outer.functor X_t (Outer.Build_FArgs X).

Module Provider_X_signature.
  Inductive signature : Set :=
  | Build_signature : signature.
End Provider_X_signature.
Definition Provider_X_signature := Provider_X_signature.signature.

Module Provider.
  Class FArgs := {
    X : Provider_X_signature;
  }.
  
  Module List.
    Definition hd `{_fargs : FArgs} {A : Set}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A} (values : list A)
      : A := RocqOfOCaml.OCamlList.hd values.
  End List.
  
  Module Provider_result.
    Record signature `{_fargs : FArgs} : Set := {
      List_hd :
        forall {A : Set}
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A}, list A -> A;
    }.
  End Provider_result.
  Definition Provider_result `{_fargs : FArgs} := @Provider_result.signature _.
  Arguments Provider_result {_}.
  
  (* Provider *)
  Definition functor `{_fargs : FArgs} :@Provider_result _fargs :=
    ({|
      Provider_result.List_hd (_fargs := _fargs) _ _ :=
        (List.hd (_fargs := _fargs))
    |} : @Provider_result _fargs).
End Provider.
Definition Provider (X : Provider_X_signature) :=
  @Provider.functor (Provider.Build_FArgs X).

Module Consumer.
  Class FArgs := {
    X : Provider_X_signature;
  }.
  
  Definition Instantiation_fargs `{_fargs : FArgs} := Provider.Build_FArgs X.
  
  Definition Instantiation `{_fargs : FArgs} :
    Provider.Provider_result (_fargs := Instantiation_fargs) := Provider X.
  
  Module List.
    Definition hd `{_fargs : FArgs} {A : Set}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A} :=
      Instantiation.(Provider.Provider_result.List_hd) (A := A).
  End List.
  
  Definition head `{_fargs : FArgs} {A : Set}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A} (values : list A)
    : A := List.hd values.
  
  Module Consumer_result.
    Record signature `{_fargs : FArgs} : Set := {
      Instantiation : Provider.Provider_result (_fargs := Instantiation_fargs);
      List_hd :
        forall {A : Set}
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A}, list A -> A;
      head :
        forall {A : Set}
          `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable A}, list A -> A;
    }.
  End Consumer_result.
  Definition Consumer_result `{_fargs : FArgs} := @Consumer_result.signature _.
  Arguments Consumer_result {_}.
  
  (* Consumer *)
  Definition functor `{_fargs : FArgs} :@Consumer_result _fargs :=
    ({|
      Consumer_result.Instantiation (_fargs := _fargs) :=
        (Instantiation (_fargs := _fargs));
      Consumer_result.List_hd (_fargs := _fargs) _ _ :=
        (List.hd (_fargs := _fargs));
      Consumer_result.head (_fargs := _fargs) _ _ := (head (_fargs := _fargs))
    |} : @Consumer_result _fargs).
End Consumer.
Definition Consumer (X : Provider_X_signature) :=
  @Consumer.functor (Consumer.Build_FArgs X).
