(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.
Unset Guard Checking.

Module state.
  Record record : Set := Build {
    remaining : int;
  }.
  Definition with_remaining remaining (r : record) :=
    Build remaining.
End state.
Definition state := state.record.

#[bypass_check(guard)]
Fixpoint run `{_rocq_guard : GeneralRecursionGuard} (current : state)
  {struct _rocq_guard} : state :=
  if equiv_decb current.(state.remaining) 0 then
    current
  else
    run {| state.remaining := Z.sub current.(state.remaining) 1; |}.
