(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.
From Stdlib Require Import Program.Wf.

Module DOMAIN.
  Record signature {t : Set} : Type := {
    t := t;
    equal : t -> t -> bool;
    zero : t;
    remainder : t -> t -> t;
  }.
End DOMAIN.
Definition DOMAIN := @DOMAIN.signature.
Arguments DOMAIN {_}.

Module Outer.
  Class FArgs {First_t : Set} := {
    First : DOMAIN (t := First_t);
  }.
  Arguments Build_FArgs {_}.
  
  Module Search.
    Class FArgs `{_fargs : FArgs} {Second_t : Set} := {
      Second : DOMAIN (t := Second_t);
    }.
    Arguments Build_FArgs {_ _ _}.
    
    Program Definition run `{_fargs : FArgs}
      (first : (Second (FArgs := _fargs)).(DOMAIN.t))
      (second : (Second (FArgs := _fargs)).(DOMAIN.t))
      : (Second (FArgs := _fargs)).(DOMAIN.t) :=
      let _rocq_measure (_rocq_state :
        (Second (FArgs := _fargs)).(DOMAIN.t) *
          (Second (FArgs := _fargs)).(DOMAIN.t)) : nat :=
        RocqOfOCaml.Basics.well_founded_measure "Outer.Search.run.loop" (_fargs,
        first, second, _rocq_state) in
      let _rocq_body :
        (forall _rocq_state :
          (Second (FArgs := _fargs)).(DOMAIN.t) *
            (Second (FArgs := _fargs)).(DOMAIN.t),
          (forall _rocq_next :
            (Second (FArgs := _fargs)).(DOMAIN.t) *
              (Second (FArgs := _fargs)).(DOMAIN.t), ltof
            ((Second (FArgs := _fargs)).(DOMAIN.t) *
              (Second (FArgs := _fargs)).(DOMAIN.t)) _rocq_measure _rocq_next
            _rocq_state -> (Second (FArgs := _fargs)).(DOMAIN.t)) ->
          (Second (FArgs := _fargs)).(DOMAIN.t)) :=
        (fun _rocq_state _rocq_recurse =>
          let '(current, next) := _rocq_state in
          if
            (Second (FArgs := _fargs)).(DOMAIN.equal) next
              (Second (FArgs := _fargs)).(DOMAIN.zero)
          then
            current
          else
            _rocq_recurse
              (next,
                ((Second (FArgs := _fargs)).(DOMAIN.remainder) current next)) _)
        in
      let _rocq_fix := @Fix
        ((Second (FArgs := _fargs)).(DOMAIN.t) *
          (Second (FArgs := _fargs)).(DOMAIN.t)) (ltof
        ((Second (FArgs := _fargs)).(DOMAIN.t) *
          (Second (FArgs := _fargs)).(DOMAIN.t)) _rocq_measure)
        (well_founded_ltof
        ((Second (FArgs := _fargs)).(DOMAIN.t) *
          (Second (FArgs := _fargs)).(DOMAIN.t)) _rocq_measure) (fun _ =>
        (Second (FArgs := _fargs)).(DOMAIN.t)) _rocq_body in
      let loop (current : (Second (FArgs := _fargs)).(DOMAIN.t))
        (next : (Second (FArgs := _fargs)).(DOMAIN.t)) :
        (Second (FArgs := _fargs)).(DOMAIN.t) := _rocq_fix (current, next) in
      let '_ := First.(DOMAIN.zero) in
      loop first second.
    
    Admit Obligations.
    
    Module Search_result.
      Record signature `{_fargs : FArgs} : Type := {
        run : Second.(DOMAIN.t) -> Second.(DOMAIN.t) -> Second.(DOMAIN.t);
      }.
    End Search_result.
    Definition Search_result `{_fargs : FArgs} := @Search_result.signature _ _ _
      _.
    Arguments Search_result {_ _ _ _}.
    
    (* Search *)
    Definition functor `{_fargs : FArgs} :@Search_result _ _ Second_t _fargs :=
      ((@Search_result.Build_signature _ _ Second_t _fargs run) :
        @Search_result _ _ Second_t _fargs).
  End Search.
  Definition Search `{_fargs : FArgs} {Second_t : Set}
    (Second : DOMAIN (t := Second_t)) :=
    @Search.functor _ _ Second_t (Search.Build_FArgs Second).
  
  Module Outer_result.
    Inductive signature `{_fargs : FArgs} : Type :=
    | Build_signature : signature.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _ _.
  Arguments Outer_result {_ _}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :@Outer_result First_t _fargs :=
    ((@Outer_result.Build_signature First_t _fargs) :
      @Outer_result First_t _fargs).
End Outer.
Definition Outer {First_t : Set} (First : DOMAIN (t := First_t)) :=
  @Outer.functor First_t (Outer.Build_FArgs First).
