(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.
From Stdlib Require Import Program.Wf.

Parameter _rocq_measure_gcd : forall (_left : int) (_right : int), nat.

Program Fixpoint gcd (_left : int) (_right : int)
  {measure (@_rocq_measure_gcd _left _right)} : int :=
  if equiv_decb _right 0 then
    _left
  else
    gcd _right (Z.rem _left _right).

Admit Obligations.

Parameter _rocq_measure_find_or : forall {A : Set}
  (default : A) (predicate : A -> bool) (values : list A), nat.

Program Fixpoint find_or {A : Set}
  (default : A) (predicate : A -> bool) (values : list A)
  {measure (@_rocq_measure_find_or A default predicate values)} : A :=
  match values with
  | [] => default
  | Datatypes.cons value values =>
    if predicate value then
      value
    else
      find_or default predicate values
  end.

Admit Obligations.
