(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Require TestProject.Provider.

Module Outer_Width_signature.
  Record signature : Type := {
    value : int;
  }.
End Outer_Width_signature.
Definition Outer_Width_signature := Outer_Width_signature.signature.

Module Outer.
  Class FArgs := {
    Width : Outer_Width_signature;
  }.
  
  Module Inner.
    Definition Repr_fargs `{_fargs : FArgs} :=
      TestProject.Provider.Fixed.Build_FArgs
        ({|
          Provider.Fixed_Width_signature.value :=
            Width.(Outer_Width_signature.value)
        |} : Provider.Fixed_Width_signature).
    
    Definition Repr `{_fargs : FArgs} :
      Provider.Fixed.Fixed_result (_fargs := Repr_fargs) :=
      (TestProject.Provider.Fixed.functor (_fargs := (Repr_fargs ))).
    
    Definition reverse `{_fargs : FArgs}
      `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
      `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
      `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable ascii}
      (value : string) : string :=
      ((Repr (_fargs := _fargs)).(Provider.Fixed.Fixed_result.reverse)
        (_rocq_assumption_0 := _rocq_assumption_0)
        (_rocq_assumption_1 := _rocq_assumption_1)
        (_rocq_assumption_2 := _rocq_assumption_2)) value.
  End Inner.
  
  Module Outer_result.
    Record signature `{_fargs : FArgs} : Type := {
      Inner_Repr :
        TestProject.Provider.Fixed.Fixed_result (_fargs := Inner.Repr_fargs);
      Inner_reverse :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable ascii}
          `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
          `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable string},
          string -> string;
    }.
  End Outer_result.
  Definition Outer_result `{_fargs : FArgs} := @Outer_result.signature _.
  Arguments Outer_result {_}.
  
  (* Outer *)
  Definition functor `{_fargs : FArgs} :@Outer_result _fargs :=
    ((@Outer_result.Build_signature _fargs Inner.Repr
      (fun _ _ _ => Inner.reverse)) : @Outer_result _fargs).
End Outer.
Definition Outer (Width : Outer_Width_signature) :=
  @Outer.functor (Outer.Build_FArgs Width).

Definition Result_fargs :=
  Outer.Build_FArgs
    (let value := 32 in
    ({|
      Outer_Width_signature.value := value
    |} : Outer_Width_signature)).

Definition Result : Outer.Outer_result (_fargs := Result_fargs) :=
  (Outer.functor (_fargs := (Result_fargs ))).

Definition reverse
  `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
  `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
  `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable ascii} : string ->
  string :=
  (Result.(Outer.Outer_result.Inner_reverse)
    (_rocq_assumption_0 := _rocq_assumption_2)
    (_rocq_assumption_1 := _rocq_assumption_1)
    (_rocq_assumption_2 := _rocq_assumption_0)).
