(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Fixed_Width_signature.
  Record signature : Type := {
    value : int;
  }.
End Fixed_Width_signature.
Definition Fixed_Width_signature := Fixed_Width_signature.signature.

Module Fixed.
  Class FArgs := {
    Width : Fixed_Width_signature;
  }.
  
  Definition t `{_fargs : FArgs} : Set := string.
  
  Definition init `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
    (f_value : int -> ascii) : string :=
    RocqOfOCaml.OCamlString.init
      (RocqOfOCaml.OCamlOption.get (Some Width.(Fixed_Width_signature.value)))
      f_value.
  
  Definition get `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable ascii}
    (value : string) (index : int) : ascii :=
    RocqOfOCaml.OCamlString.get value index.
  
  Definition reverse `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
    `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
    `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable ascii}
    (value : string) : string :=
    (init (_rocq_assumption_0 := _rocq_assumption_0)
      (_rocq_assumption_1 := _rocq_assumption_1))
      (fun (index : int) =>
        (get (_rocq_assumption_0 := _rocq_assumption_2)) value
          (Z.sub (Z.sub Width.(Fixed_Width_signature.value) index) 1)).
  
  Module Fixed_result.
    Record signature `{_fargs : FArgs} : Type := {
      t := string;
      init :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
          `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int},
          (int -> ascii) -> string;
      get :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable ascii},
          string -> int -> ascii;
      reverse :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable string}
          `{_rocq_assumption_1 : RocqOfOCaml.Basics.Unreachable int}
          `{_rocq_assumption_2 : RocqOfOCaml.Basics.Unreachable ascii},
          string -> string;
    }.
  End Fixed_result.
  Definition Fixed_result `{_fargs : FArgs} := @Fixed_result.signature _.
  Arguments Fixed_result {_}.
  
  (* Fixed *)
  Definition functor `{_fargs : FArgs} :@Fixed_result _fargs :=
    ((@Fixed_result.Build_signature _fargs (fun _ _ => init) (fun _ => get)
      (fun _ _ _ => reverse)) : @Fixed_result _fargs).
End Fixed.
Definition Fixed (Width : Fixed_Width_signature) :=
  @Fixed.functor (Fixed.Build_FArgs Width).
