(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Make_Argument_signature.
  Record signature : Type := {
    value : int;
  }.
End Make_Argument_signature.
Definition Make_Argument_signature := Make_Argument_signature.signature.

Module Make.
  Class FArgs := {
    Argument : Make_Argument_signature;
  }.
  
  Definition value `{_fargs : FArgs} : int :=
    Argument.(Make_Argument_signature.value).
  
  Definition missing `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int} (flag : bool)
    : int :=
    if flag then
      value
    else
      let '_ := false in
      (@RocqOfOCaml.Basics.unreachable int _).
  
  Module Make_result.
    Record signature `{_fargs : FArgs} : Type := {
      value : int;
      missing :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable int},
          bool -> int;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _.
  Arguments Make_result {_}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result _fargs :=
    ((@Make_result.Build_signature _fargs value (fun _ => missing)) :
      @Make_result _fargs).
End Make.
Definition Make (Argument : Make_Argument_signature) :=
  @Make.functor (Make.Build_FArgs Argument).
