(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module ELEMENT.
  Record signature {t : Set} : Type := {
    t := t;
    zero : t;
  }.
End ELEMENT.
Definition ELEMENT := @ELEMENT.signature.
Arguments ELEMENT {_}.

Module Operations.
  Class FArgs {Element_t : Set} := {
    Element : ELEMENT (t := Element_t);
  }.
  Arguments Build_FArgs {_}.
  
  Definition get `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Element.(ELEMENT.t)}
    (function_parameter : unit) : Element.(ELEMENT.t) :=
    let '_ := function_parameter in
    if true then
      Element.(ELEMENT.zero)
    else
      let '_ := "unreachable" in
      (@RocqOfOCaml.Basics.unreachable Element.(ELEMENT.t) _).
  
  Definition check `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable bool}
    (function_parameter : unit) : bool :=
    let '_ := function_parameter in
    if true then
      true
    else
      let '_ := "unreachable" in
      (@RocqOfOCaml.Basics.unreachable bool _).
  
  Module Operations_result.
    Record signature `{_fargs : FArgs} : Type := {
      get :
        forall
          `{_rocq_assumption_0 :
            RocqOfOCaml.Basics.Unreachable Element.(ELEMENT.t)},
          unit -> Element.(ELEMENT.t);
      check :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable bool},
          unit -> bool;
    }.
  End Operations_result.
  Definition Operations_result `{_fargs : FArgs} := @Operations_result.signature
    _ _.
  Arguments Operations_result {_ _}.
  
  (* Operations *)
  Definition functor `{_fargs : FArgs} :@Operations_result Element_t _fargs :=
    ((@Operations_result.Build_signature Element_t _fargs (fun _ => get)
      (fun _ => check)) : @Operations_result Element_t _fargs).
End Operations.
Definition Operations {Element_t : Set} (Element : ELEMENT (t := Element_t)) :=
  @Operations.functor Element_t (Operations.Build_FArgs Element).

Module Extension_Modulus_signature.
  Record signature {Element_t : Set} {Element : ELEMENT (t := Element_t)} : Type
    := {
    modulus : Element.(ELEMENT.t);
  }.
End Extension_Modulus_signature.
Definition Extension_Modulus_signature {Element_t : Set}
  {Element : ELEMENT (t := Element_t)} := @Extension_Modulus_signature.signature
  Element_t Element.

Module Extension.
  Class FArgs {Element_t : Set} := {
    Element : ELEMENT (t := Element_t);
    Modulus : (Extension_Modulus_signature (Element := Element));
  }.
  Arguments Build_FArgs {_}.
  
  Definition Operations_include_fargs `{_fargs : FArgs} :=
    Operations.Build_FArgs Element.
  
  Definition Operations_include `{_fargs : FArgs} :
    Operations.Operations_result (_fargs := Operations_include_fargs) :=
    (Operations.functor (_fargs := (Operations_include_fargs ))).
  
  (** Inclusion of the module [Operations_include] *)
  Definition get `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Element.(ELEMENT.t)} :
    unit -> Element.(ELEMENT.t) :=
    (Operations_include (_fargs := _fargs)).(Operations.Operations_result.get)
      (_rocq_assumption_0 := _rocq_assumption_0).
  
  Definition check `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable bool} : unit -> bool
    :=
    (Operations_include (_fargs := _fargs)).(Operations.Operations_result.check)
      (_rocq_assumption_0 := _rocq_assumption_0).
  
  Definition value `{_fargs : FArgs} : Element.(ELEMENT.t) :=
    Modulus.(Extension_Modulus_signature.modulus).
  
  Module Extension_result.
    Record signature `{_fargs : FArgs} : Type := {
      get :
        forall
          `{_rocq_assumption_0 :
            RocqOfOCaml.Basics.Unreachable Element.(ELEMENT.t)},
          unit -> Element.(ELEMENT.t);
      check :
        forall `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable bool},
          unit -> bool;
      value : Element.(ELEMENT.t);
    }.
  End Extension_result.
  Definition Extension_result `{_fargs : FArgs} := @Extension_result.signature _
    _.
  Arguments Extension_result {_ _}.
  
  (* Extension *)
  Definition functor `{_fargs : FArgs} :@Extension_result Element_t _fargs :=
    ((@Extension_result.Build_signature Element_t _fargs (fun _ => get)
      (fun _ => check) value) : @Extension_result Element_t _fargs).
End Extension.
Definition Extension {Element_t : Set}
  (Element : ELEMENT (t := Element_t))
  (Modulus : (Extension_Modulus_signature (Element := Element))) :=
  @Extension.functor Element_t (Extension.Build_FArgs Element Modulus).

Module Packaged.
  Class FArgs {Element_t : Set} := {
    Element : ELEMENT (t := Element_t);
    _rocq_projection_assumption_0 : RocqOfOCaml.Basics.Unreachable bool;
  }.
  Arguments Build_FArgs {_} _ {_}.
  
  #[local] Instance _rocq_projection_assumption_0_instance `{_fargs : FArgs} :
    RocqOfOCaml.Basics.Unreachable bool := _rocq_projection_assumption_0.
  
  
  
  Definition Applied_fargs `{_fargs : FArgs} :=
    Extension.Build_FArgs Element
      (let modulus :=
        let opened_module_568 := Operations Element in
        if
          (opened_module_568.(Operations.Operations_result.check)
            (_rocq_assumption_0 := _rocq_projection_assumption_0)) tt
        then
          Element.(ELEMENT.zero)
        else
          Element.(ELEMENT.zero) in
      ({|
        Extension_Modulus_signature.modulus := modulus
      |} : Extension_Modulus_signature)).
  
  Definition Applied `{_fargs : FArgs} :
    Extension.Extension_result (_fargs := Applied_fargs) := (Extension.functor
    (_fargs := (Applied_fargs ))).
  
  (** Inclusion of the module [Applied] *)
  Definition get `{_fargs : FArgs}
    `{_rocq_assumption_0 : RocqOfOCaml.Basics.Unreachable Element.(ELEMENT.t)} :
    unit -> Element.(ELEMENT.t) :=
    (Applied (_fargs := _fargs)).(Extension.Extension_result.get)
      (_rocq_assumption_0 := _rocq_assumption_0).
  
  Definition check `{_fargs : FArgs} : unit -> bool :=
    (Applied (_fargs := _fargs)).(Extension.Extension_result.check)
      (_rocq_assumption_0 := _rocq_projection_assumption_0).
  
  Definition value `{_fargs : FArgs} : Element.(ELEMENT.t) :=
    (Applied (_fargs := _fargs)).(Extension.Extension_result.value).
  
  Module Packaged_result.
    Record signature `{_fargs : FArgs} : Type := {
      Applied : Extension.Extension_result (_fargs := Applied_fargs);
      get :
        forall
          `{_rocq_assumption_0 :
            RocqOfOCaml.Basics.Unreachable Element.(ELEMENT.t)},
          unit -> Element.(ELEMENT.t);
      check : unit -> bool;
      value : Element.(ELEMENT.t);
    }.
  End Packaged_result.
  Definition Packaged_result `{_fargs : FArgs} := @Packaged_result.signature _
    _.
  Arguments Packaged_result {_ _}.
  
  (* Packaged *)
  Definition functor `{_fargs : FArgs} :@Packaged_result Element_t _fargs :=
    ((@Packaged_result.Build_signature Element_t _fargs Applied (fun _ => get)
      check value) : @Packaged_result Element_t _fargs).
End Packaged.
Definition Packaged {Element_t : Set} (Element : ELEMENT (t := Element_t))
  `{_rocq_projection_assumption_0 : RocqOfOCaml.Basics.Unreachable bool} :=
  @Packaged.functor Element_t (Packaged.Build_FArgs Element).
