(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module SIG.
  Record signature {t : Set -> Set} : Type := {
    t := t;
    _return : forall {a : Set} , a -> t a;
    op_gtgteq : forall {a b : Set} , t a -> (a -> t b) -> t b;
  }.
End SIG.
Definition SIG := @SIG.signature.
Arguments SIG {_}.

Module SIG_MONAD := SIG.
Definition SIG_MONAD := @SIG_MONAD.signature.
Arguments SIG_MONAD {_}.

Module Make.
  Class FArgs {M_t : Set -> Set} := {
    M : SIG (t := M_t);
  }.
  Arguments Build_FArgs {_}.
  
  (** Inclusion of the module [M] *)
  Definition t `{_fargs : FArgs} (a : Set) := M.(SIG_MONAD.t) a.
  
  Definition _return `{_fargs : FArgs} {a : Set} : a -> t a :=
    M.(SIG_MONAD._return).
  
  Definition op_gtgteq `{_fargs : FArgs} {a b : Set} : t a -> (a -> t b) -> t b
    := M.(SIG_MONAD.op_gtgteq).
  
  Definition map `{_fargs : FArgs} {A B : Set}
    (f_value : A -> B) (x_value : M.(SIG_MONAD.t) A) : M.(SIG_MONAD.t) B :=
    (M.(SIG_MONAD.op_gtgteq) (b := B) (a := A)) x_value
      (fun (x_value : A) => (M.(SIG_MONAD._return) (a := B)) (f_value x_value)).
  
  Module Make_result.
    Record signature `{_fargs : FArgs} : Type := {
      t := fun (a : Set) => t a;
      _return : forall {a : Set} , a -> t a;
      op_gtgteq : forall {a b : Set} , t a -> (a -> t b) -> t b;
      map : forall {A B : Set} , (A -> B) -> t A -> t B;
    }.
  End Make_result.
  Definition Make_result `{_fargs : FArgs} := @Make_result.signature _ _.
  Arguments Make_result {_ _}.
  
  (* Make *)
  Definition functor `{_fargs : FArgs} :@Make_result M_t _fargs :=
    ((@Make_result.Build_signature M_t _fargs (fun _ => _return)
      (fun _ _ => op_gtgteq) (fun _ _ => map)) : @Make_result M_t _fargs).
End Make.
Definition Make {M_t : Set -> Set} (M : SIG (t := M_t)) :=
  @Make.functor M_t (Make.Build_FArgs M).

Module Make_Monad := Make.
Definition Make_Monad := @Make.
Arguments Make_Monad : default implicits.

Module TRANS.
  Record signature {t : Set -> Set} {Inner_t : Set -> Set} : Type := {
    t := t;
    _return : forall {a : Set} , a -> t a;
    op_gtgteq : forall {a b : Set} , t a -> (a -> t b) -> t b;
    Inner : SIG (t := Inner_t);
    lift : forall {a : Set} , Inner_t a -> t a;
  }.
End TRANS.
Definition TRANS := @TRANS.signature.
Arguments TRANS {_ _}.
